

export const stylePrompts: { [key: number]: string } = {
  1: "Keep the image exactly as is, no artistic transformation",
  2: "Render this image in the style of a traditional oil painting — natural lighting, fine brushwork, soft textures, and elegant realism on canvas — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  3: "Repaint this image with delicate watercolor — light washes, soft pigment bleeds, fluid brushstrokes, and subtle gradients — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  4: "Reinterpret this image in an expressive watercolor style — bold strokes, vibrant splashes, unpredictable color flow, and visible brush textures — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  5: "Redraw this in soft pastel — chalky textures, smooth blending, gentle shadows, and realistic contours with calming tones — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  6: "Transform into abstract low poly art — angular shapes, stylized fragmentation, and a bold, geometric reinterpretation using vibrant polygons — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  7: "Convert to 3D animated Pixar style — smooth shading, expressive features, clean modeling, and vibrant cartoon aesthetics — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  8: "Sketch this image in detailed charcoal — hand-drawn textures, dramatic shading, monochrome tones, and bold contrast — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  9: "Apply bold pop art style — saturated color blocks, halftone dots, thick outlines, and retro comic book vibes — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  10: "Paint this in Neon Splash style — glowing drips, vibrant neon explosions, high contrast strokes, and energetic paint effects — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  11: "Stylize with electric neon glow — radiant edges, high contrast lighting, and pulsing neon colors for a vivid, futuristic look — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  12: "Create an artistic mashup style version of this image with bold, expressive, and unique creative elements — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  13: "Create abstract fusion art — blend watercolor, digital textures, and geometric patterns into a cohesive, expressive, multi-style composition — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  14: "Recreate with embroidery texture — intricate stitch details, textile-like depth, and hand-sewn artistic styling — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure.",
  15: "Redesign in modern Art Deco — geometric elegance, bold symmetry, metallic accents, and refined lines — while preserving exact facial features, including eye color, expression, and proportions. Do not change pose, markings, expression, or anatomical structure."
};

