
export const stylePrompts: { [key: number]: string } = {
  1: "Keep the image exactly as is, no artistic transformation",
  2: "Transform this image into a traditional oil painting style with natural lighting, fine brushwork, soft textures, and elegant realism on canvas. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  3: "Apply delicate watercolor effects with light washes, soft pigment bleeds, fluid brushstrokes, and subtle gradients. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  4: "Create an expressive watercolor style with bold strokes, vibrant splashes, unpredictable color flow, and visible brush textures. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  5: "Render in soft pastel style with chalky textures, smooth blending, gentle shadows, and realistic contours with calming tones. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  6: "Transform into abstract low poly art with angular shapes, stylized fragmentation, and bold geometric reinterpretation using vibrant polygons. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  7: "Convert to 3D animated Pixar style with smooth shading, expressive features, clean modeling, and vibrant cartoon aesthetics. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  8: "Create a detailed charcoal sketch with hand-drawn textures, dramatic shading, monochrome tones, and bold contrast. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  9: "Apply bold pop art style with saturated color blocks, halftone dots, thick outlines, and retro comic book vibes. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  10: "Paint in Neon Splash style with glowing drips, vibrant neon explosions, high contrast strokes, and energetic paint effects. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  11: "Stylize with electric neon glow effects - radiant edges, high contrast lighting, and pulsing neon colors for a vivid, futuristic look. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  12: "Create an artistic mashup style with bold, expressive, and unique creative elements. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  13: "Create abstract fusion art by blending watercolor, digital textures, and geometric patterns into a cohesive, expressive, multi-style composition. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  14: "Recreate with embroidery texture featuring intricate stitch details, textile-like depth, and hand-sewn artistic styling. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
  15: "Redesign in modern Art Deco style with geometric elegance, bold symmetry, metallic accents, and refined lines. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics."
};
