// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run `npm run build:registry` to regenerate.

import type { StyleRegistryEntry } from '../types';

export const TONE_STYLES: StyleRegistryEntry[] = [
{
  id: "hex-weave",
  slug: "hex-weave",
  name: "Hex Weave",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Interlocking hexagonal tessellations with soft gradients and woven light.",
  marketingCopy: "Wrap your portrait in geometric weaving—honeycomb planes, gleaming threads, and luminous negative space.",
  badges: ["abstract"],
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/hex-weave.jpg",
    thumbnailWebp: "/art-style-thumbnails/hex-weave.webp",
    thumbnailAvif: "/art-style-thumbnails/hex-weave.avif",
    preview: "/art-style-thumbnails/hex-weave.jpg",
    previewWebp: "/art-style-thumbnails/hex-weave.webp",
    previewAvif: "/art-style-thumbnails/hex-weave.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 29,
    prompt: "Recreate the exact image as an isometric hex weave—textile, dimensional, and readable. Preserve the subject’s full composition and a clean silhouette. Implement over/under weaving logic with subtle cast shadows. Increase strand density around eyes and lips for detail; use larger, looser weave on hair and background. Render strands with soft fiber sheen (matte to satin), avoiding photographic texture. Keep pupils and key features partially un-woven for identity; palette stays tasteful with one accent color thread.",
    updatedAt: "2025-10-30 03:26:58.086611+00",
  },
  story: null,
},
{
  id: "prisma-tesla",
  slug: "prisma-tesla",
  name: "Prisma Tesla",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Electro-spectrum prisms and field lines bending portrait contours.",
  marketingCopy: "Charge your art with neon prismatic flares, kinetic filaments, and energized negative space.",
  badges: ["abstract"],
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/prisma-tesla.jpg",
    thumbnailWebp: "/art-style-thumbnails/prisma-tesla.webp",
    thumbnailAvif: "/art-style-thumbnails/prisma-tesla.avif",
    preview: "/art-style-thumbnails/prisma-tesla.jpg",
    previewWebp: "/art-style-thumbnails/prisma-tesla.webp",
    previewAvif: "/art-style-thumbnails/prisma-tesla.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 30,
    prompt: "Recreate the exact image as a low-poly prism composition—faceted, crisp, and high-impact. Preserve full structure and pose. Triangulate forms with Delaunay-like facets; use finer facets around eyes and mouth, larger facets elsewhere. Assign each triangle a cohesive color ramp with mild hue shift; add slim bevel highlights on key edges, no heavy outlines. Introduce a few spectral light leaks near specular zones; keep skin tones stylized but believable. Background is dark-to-mid with soft bokeh sparkles; no facet overdraw on pupils.",
    updatedAt: "2025-10-30 03:27:34.727397+00",
  },
  story: null,
},
{
  id: "op-art-pulse",
  slug: "op-art-pulse",
  name: "Op Art Pulse",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Hypnotic moiré bands and vibrating contrasts with portrait silhouettes.",
  marketingCopy: "Spin optical rhythms around your subject—pulsing wave grids, stark monochrome beats, and kinetic energy.",
  badges: ["abstract"],
  sortOrder: 100,
  assets: {
    thumbnail: "/art-style-thumbnails/op-art-pulse.jpg",
    thumbnailWebp: "/art-style-thumbnails/op-art-pulse.webp",
    thumbnailAvif: "/art-style-thumbnails/op-art-pulse.avif",
    preview: "/art-style-thumbnails/op-art-pulse.jpg",
    previewWebp: "/art-style-thumbnails/op-art-pulse.webp",
    previewAvif: "/art-style-thumbnails/op-art-pulse.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 31,
    prompt: "Recreate the exact image in an optical art style — rhythmic, high-contrast patterns that create vibration and depth. Use a restrained palette (black/white or limited duotone) and control line frequency so features remain readable. Employ gradient line spacing to model volume and a subtle background field that pulses outward from the silhouette. The result should feel kinetic and mesmerizing — a crisp optical illusion that still honors the subject’s identity.",
    updatedAt: "2025-10-30 03:28:33.633157+00",
  },
  story: null,
},
{
  id: "casso-cubist",
  slug: "casso-cubist",
  name: "Casso Cubist",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Shattered planes, angular faceting, and gallery-grade cubist lighting.",
  marketingCopy: "Unlock cubist geometry—braided viewpoints, luxe palettes, and sculpted planes worthy of a salon wall.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/casso-cubist.jpg",
    thumbnailWebp: "/art-style-thumbnails/casso-cubist.webp",
    thumbnailAvif: "/art-style-thumbnails/casso-cubist.avif",
    preview: "/art-style-thumbnails/casso-cubist.jpg",
    previewWebp: "/art-style-thumbnails/casso-cubist.webp",
    previewAvif: "/art-style-thumbnails/casso-cubist.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 32,
    prompt: "Recreate the exact image in Synthetic Cubism — bold collage logic with graphic shapes and inserts. Preserve the composition and readable proportions of the subject, then rebuild forms using larger flat planes, cut-paper edges, and selective contour lines. Integrate collage elements (newsprint textures, music-staff scraps, woodgrain, painted labels) as surface inlays; keep them abstract and non-readable. Use a warmer, more playful palette (tan, cream, coral, olive, charcoal) with 1–2 accent colors. Outline only where needed; let overlapping shapes and stamped textures imply volume. The result should feel modern, witty, and constructed — a lively cubist collage that still honors the source image.",
    updatedAt: "2025-10-30 03:29:16.55469+00",
  },
  story: null,
},
{
  id: "sumi-ink-whisper",
  slug: "sumi-ink-whisper",
  name: "Sumi Ink Whisper",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Feathered ink washes and serene negative space with meditative linework.",
  marketingCopy: "Unlock tranquil sumi expression—floating washes, quiet gradients, and lyrical brush cadence.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/sumi-ink-whisper.jpg",
    thumbnailWebp: "/art-style-thumbnails/sumi-ink-whisper.webp",
    thumbnailAvif: "/art-style-thumbnails/sumi-ink-whisper.avif",
    preview: "/art-style-thumbnails/sumi-ink-whisper.jpg",
    previewWebp: "/art-style-thumbnails/sumi-ink-whisper.webp",
    previewAvif: "/art-style-thumbnails/sumi-ink-whisper.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 33,
    prompt: "Recreate the exact image as a sumi-ink marbling portrait—fluid, poetic, and atmospheric. Preserve composition and a clean silhouette. Reduce to a desaturated ink base, then advect soft marbling flows along cheek and hair contours; keep eyes, nostrils, and lip edges sharper for identity. Layer delicate gold-foil veins across broad ink pools; use feathered edges and paper grain. Avoid chaotic turbulence over the eye triangle. Add faint bloom around highlights; background remains a calm marbled wash.",
    updatedAt: "2025-10-30 03:30:08.333804+00",
  },
  story: null,
},
{
  id: "abstract-chorus",
  slug: "abstract-chorus",
  name: "Abstract Chorus",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Layered color harmonies with musical arcs and gestural echoes.",
  marketingCopy: "Unlock a chorus of color—syncopated arcs, lyrical gradients, and resonant painterly movement.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 130,
  assets: {
    thumbnail: "/art-style-thumbnails/abstract-chorus.jpg",
    thumbnailWebp: "/art-style-thumbnails/abstract-chorus.webp",
    thumbnailAvif: "/art-style-thumbnails/abstract-chorus.avif",
    preview: "/art-style-thumbnails/abstract-chorus.jpg",
    previewWebp: "/art-style-thumbnails/abstract-chorus.webp",
    previewAvif: "/art-style-thumbnails/abstract-chorus.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 34,
    prompt: "Recreate the exact image as an Orphist color-harmony—prismatic, circular, and musical. Preserve overall structure and a clean silhouette. Build the background with translucent discs and curved arcs that radiate behind and around the silhouette. \\n",
    updatedAt: "2025-10-30 03:30:50.144199+00",
  },
  story: null,
}
];

export const TONE_STYLES_BY_ID = new Map(TONE_STYLES.map((s) => [s.id, s]));
