// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run `npm run build:registry` to regenerate.

import type { StyleRegistryEntry } from '../types';

export const TONE_STYLES: StyleRegistryEntry[] = [
{
  id: "hex-weave",
  slug: "hex-weave",
  name: "Hex Weave",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Interlocking hexagonal tessellations with soft gradients and woven light.",
  marketingCopy: "Wrap your portrait in geometric weaving—honeycomb planes, gleaming threads, and luminous negative space.",
  badges: ["abstract"],
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/hex-weave.jpg",
    thumbnailWebp: "/art-style-thumbnails/hex-weave.webp",
    thumbnailAvif: "/art-style-thumbnails/hex-weave.avif",
    preview: "/art-style-thumbnails/hex-weave.jpg",
    previewWebp: "/art-style-thumbnails/hex-weave.webp",
    previewAvif: "/art-style-thumbnails/hex-weave.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  story: null,
},
{
  id: "prisma-tesla",
  slug: "prisma-tesla",
  name: "Prisma Tesla",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Electro-spectrum prisms and field lines bending portrait contours.",
  marketingCopy: "Charge your art with neon prismatic flares, kinetic filaments, and energized negative space.",
  badges: ["abstract"],
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/prisma-tesla.jpg",
    thumbnailWebp: "/art-style-thumbnails/prisma-tesla.webp",
    thumbnailAvif: "/art-style-thumbnails/prisma-tesla.avif",
    preview: "/art-style-thumbnails/prisma-tesla.jpg",
    previewWebp: "/art-style-thumbnails/prisma-tesla.webp",
    previewAvif: "/art-style-thumbnails/prisma-tesla.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  story: null,
},
{
  id: "op-art-pulse",
  slug: "op-art-pulse",
  name: "Op Art Pulse",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Hypnotic moiré bands and vibrating contrasts with portrait silhouettes.",
  marketingCopy: "Spin optical rhythms around your subject—pulsing wave grids, stark monochrome beats, and kinetic energy.",
  badges: ["abstract"],
  sortOrder: 100,
  assets: {
    thumbnail: "/art-style-thumbnails/op-art-pulse.jpg",
    thumbnailWebp: "/art-style-thumbnails/op-art-pulse.webp",
    thumbnailAvif: "/art-style-thumbnails/op-art-pulse.avif",
    preview: "/art-style-thumbnails/op-art-pulse.jpg",
    previewWebp: "/art-style-thumbnails/op-art-pulse.webp",
    previewAvif: "/art-style-thumbnails/op-art-pulse.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  story: null,
},
{
  id: "casso-cubist",
  slug: "casso-cubist",
  name: "Casso Cubist",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Shattered planes, angular faceting, and gallery-grade cubist lighting.",
  marketingCopy: "Unlock cubist geometry—braided viewpoints, luxe palettes, and sculpted planes worthy of a salon wall.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/casso-cubist.jpg",
    thumbnailWebp: "/art-style-thumbnails/casso-cubist.webp",
    thumbnailAvif: "/art-style-thumbnails/casso-cubist.avif",
    preview: "/art-style-thumbnails/casso-cubist.jpg",
    previewWebp: "/art-style-thumbnails/casso-cubist.webp",
    previewAvif: "/art-style-thumbnails/casso-cubist.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  story: null,
},
{
  id: "sumi-ink-whisper",
  slug: "sumi-ink-whisper",
  name: "Sumi Ink Whisper",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Feathered ink washes and serene negative space with meditative linework.",
  marketingCopy: "Unlock tranquil sumi expression—floating washes, quiet gradients, and lyrical brush cadence.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/sumi-ink-whisper.jpg",
    thumbnailWebp: "/art-style-thumbnails/sumi-ink-whisper.webp",
    thumbnailAvif: "/art-style-thumbnails/sumi-ink-whisper.avif",
    preview: "/art-style-thumbnails/sumi-ink-whisper.jpg",
    previewWebp: "/art-style-thumbnails/sumi-ink-whisper.webp",
    previewAvif: "/art-style-thumbnails/sumi-ink-whisper.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  story: null,
},
{
  id: "abstract-chorus",
  slug: "abstract-chorus",
  name: "Abstract Chorus",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Layered color harmonies with musical arcs and gestural echoes.",
  marketingCopy: "Unlock a chorus of color—syncopated arcs, lyrical gradients, and resonant painterly movement.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 130,
  assets: {
    thumbnail: "/art-style-thumbnails/abstract-chorus.jpg",
    thumbnailWebp: "/art-style-thumbnails/abstract-chorus.webp",
    thumbnailAvif: "/art-style-thumbnails/abstract-chorus.avif",
    preview: "/art-style-thumbnails/abstract-chorus.jpg",
    previewWebp: "/art-style-thumbnails/abstract-chorus.webp",
    previewAvif: "/art-style-thumbnails/abstract-chorus.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  story: null,
}
];

export const TONE_STYLES_BY_ID = new Map(TONE_STYLES.map((s) => [s.id, s]));
