// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run `npm run build:registry` to regenerate.

import type { StyleRegistryEntry } from '../types';

export const TONE_STYLES: StyleRegistryEntry[] = [
{
  id: "plush-figure",
  slug: "plush-figure",
  name: "Plush Figure",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Hand-sewn felt panels and cozy stitches.",
  marketingCopy: "Transform your portrait into a plush keepsake—hand-stitched felt seams, soft stuffing, and storybook charm.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/plush-figure.jpg",
    thumbnailWebp: "/art-style-thumbnails/plush-figure.webp",
    thumbnailAvif: "/art-style-thumbnails/plush-figure.avif",
    preview: "/art-style-thumbnails/plush-figure.jpg",
    previewWebp: "/art-style-thumbnails/plush-figure.webp",
    previewAvif: "/art-style-thumbnails/plush-figure.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 44,
    prompt: "Recreate the exact image as a hand-sewn felt plush—soft, stitched, and huggable. Preserve the subject’s composition and clean silhouette, then rebuild forms as layered felt panels with visible blanket stitches along edges, occasional cross-stitches, and tiny fabric seams. Use matte wool-fiber texture with light fuzz; add gentle poly-fill puffing for rounded volume. Replace eyes/emblems with button or embroidered details; no photographic surfaces. Keep colors cozy and slightly desaturated; add subtle fabric shadowing and tabletop studio light for depth.",
    updatedAt: "2025-10-30 22:19:21.165638+00",
  },
  story: null,
},
{
  id: "candy-gummy",
  slug: "candy-gummy",
  name: "Candy Gummy",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Translucent jelly glow with tiny bubbles.",
  marketingCopy: "Render your photo as a gummy treat—sparkling translucency, candy hues, and gleaming sugar bubbles suspended inside.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/candy-gummy.jpg",
    thumbnailWebp: "/art-style-thumbnails/candy-gummy.webp",
    thumbnailAvif: "/art-style-thumbnails/candy-gummy.avif",
    preview: "/art-style-thumbnails/candy-gummy.jpg",
    previewWebp: "/art-style-thumbnails/candy-gummy.webp",
    previewAvif: "/art-style-thumbnails/candy-gummy.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 45,
    prompt: "Recreate the exact image as a translucent gummy candy—edible, glossy, and playful. Preserve the silhouette and readable proportions; soften forms into rounded, jellylike geometry with subsurface glow. Render materials as tinted gelatin with tiny suspended air bubbles, smooth meniscus edges, and gentle stickiness; add specular highlights and soft internal caustics. Use a bright candy palette; optional “sugar sparkle” variant with fine crystalline dusting on outer surfaces. Background simple and clean to emphasize translucency.",
    updatedAt: "2025-10-30 22:19:43.914864+00",
  },
  story: null,
},
{
  id: "action-figure",
  slug: "action-figure",
  name: "Action Figure",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Poseable toy geometry with clean joints.",
  marketingCopy: "Strike a heroic pose—collector-grade plastic forms, snap-fit armor, and precise articulation points on every limb.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 100,
  assets: {
    thumbnail: "/art-style-thumbnails/action-figure.jpg",
    thumbnailWebp: "/art-style-thumbnails/action-figure.webp",
    thumbnailAvif: "/art-style-thumbnails/action-figure.avif",
    preview: "/art-style-thumbnails/action-figure.jpg",
    previewWebp: "/art-style-thumbnails/action-figure.webp",
    previewAvif: "/art-style-thumbnails/action-figure.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 46,
    prompt: "Recreate the exact image as an action figure—glossy PVC/ABS, collectible, and retail-ready. Preserve the subject’s composition and clean silhouette, then rebuild forms with panel breaks, visible injection-mold seams, and articulated joints (ball shoulders/hips, hinge elbows/knees, cut wrists/neck or equivalent connectors). Replace textures with crisp color blocking and tampo-printed decals; no photographic surfaces.",
    updatedAt: "2025-10-30 22:21:01.249607+00",
  },
  story: null,
},
{
  id: "porcelain-figurine",
  slug: "porcelain-figurine",
  name: "Porcelain Figurine",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Glazed ceramic shine with gold trim.",
  marketingCopy: "Elevate every detail with porcelain glaze, lustrous highlights, and hand-painted gold filigree worthy of a display cabinet.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/porcelain-figurine.jpg",
    thumbnailWebp: "/art-style-thumbnails/porcelain-figurine.webp",
    thumbnailAvif: "/art-style-thumbnails/porcelain-figurine.avif",
    preview: "/art-style-thumbnails/porcelain-figurine.jpg",
    previewWebp: "/art-style-thumbnails/porcelain-figurine.webp",
    previewAvif: "/art-style-thumbnails/porcelain-figurine.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 43,
    prompt: "Recreate the exact image as a porcelain figurine — high-gloss glaze, smooth sculpted planes, and hand-painted gold trim. Preserve the original pose and expression with refined, slightly idealized anatomy. Add delicate floral or filigree accents around clothing edges. Lighting should include bright highlights and subtle reflections characteristic of kiln-fired ceramic. Present on a small pedestal or tabletop shadow with a soft studio backdrop.",
    updatedAt: "2025-10-30T07:16:07.570425+00",
  },
  story: null,
},
{
  id: "ice-sculpture",
  slug: "ice-sculpture",
  name: "Ice Sculpture",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Chisel-cut crystal with frosty edges.",
  marketingCopy: "Carve your subject from crystal-clear ice—faceted planes, frosted edges, and refractive glow straight from a winter gala.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/ice-sculpture.jpg",
    thumbnailWebp: "/art-style-thumbnails/ice-sculpture.webp",
    thumbnailAvif: "/art-style-thumbnails/ice-sculpture.avif",
    preview: "/art-style-thumbnails/ice-sculpture.jpg",
    previewWebp: "/art-style-thumbnails/ice-sculpture.webp",
    previewAvif: "/art-style-thumbnails/ice-sculpture.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 47,
    prompt: "Recreate the exact image as a carved ice sculpture—crystalline, frosted, and event-ready. Preserve structure and silhouette; translate planes into chisel facets, bevels, and shallow relief cuts. Material: clear ice with internal cracks, faint bubbles, and edge frost; cooler blue-white rim light and subtle volumetric fog. Seat the piece on a pedestal or banquet plinth with a thin melt pool and soft reflections. Keep surfaces clean and glassy where freshly cut; heavier frost in shadowed recesses.",
    updatedAt: "2025-10-30 22:21:39.356445+00",
  },
  story: null,
},
{
  id: "bronze-statue",
  slug: "bronze-statue",
  name: "Bronze Statue",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Cast-metal patina on a plinth.",
  marketingCopy: "Celebrate timeless craftsmanship—cast bronze patina, engraved plinth, and gallery-ready museum lighting.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 130,
  assets: {
    thumbnail: "/art-style-thumbnails/bronze-statue.jpg",
    thumbnailWebp: "/art-style-thumbnails/bronze-statue.webp",
    thumbnailAvif: "/art-style-thumbnails/bronze-statue.avif",
    preview: "/art-style-thumbnails/bronze-statue.jpg",
    previewWebp: "/art-style-thumbnails/bronze-statue.webp",
    previewAvif: "/art-style-thumbnails/bronze-statue.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 48,
    prompt: "Recreate the exact image as a cast bronze statue—monumental, weighty, and timeless. Preserve overall structure and a clean silhouette; translate forms into metal with crisp chisel/tool detail and softened edges from casting. Render a dark bronze alloy with subtle patina (green/teal in recesses), warm speculars on highlights, and faint foundry seam hints; mount on a stone or plinth base with engraved plate. Keep surfaces matte-to-satin, no photographic texture; add gentle museum lighting with cool rim to reveal volume.",
    updatedAt: "2025-10-30 22:22:18.252698+00",
  },
  story: null,
},
{
  id: "wax-candle",
  slug: "wax-candle",
  name: "Wax Candle",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Translucent wax with wick and soft drips.",
  marketingCopy: "Melt into a luminous candle form—translucent wax, glowing core, and delicate drips descending toward the base.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 140,
  assets: {
    thumbnail: "/art-style-thumbnails/wax-candle.jpg",
    thumbnailWebp: "/art-style-thumbnails/wax-candle.webp",
    thumbnailAvif: "/art-style-thumbnails/wax-candle.avif",
    preview: "/art-style-thumbnails/wax-candle.jpg",
    previewWebp: "/art-style-thumbnails/wax-candle.webp",
    previewAvif: "/art-style-thumbnails/wax-candle.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 49,
    prompt: "Recreate the exact image as a sculpted wax candle—translucent, glossy, and gently melting. Preserve proportions and silhouette; simplify into smooth wax planes with subtle tool impressions, poured seams, and soft rounded edges. Material: tinted paraffin/beeswax with visible subsurface glow; include a centered wick and mild heat-softened sagging or drip trails. Optional lit variant with small flame, warm halo, and pooling wax at the base; place on a simple heat-safe dish.",
    updatedAt: "2025-10-30 22:22:43.041383+00",
  },
  story: null,
},
{
  id: "sand-sculpture",
  slug: "sand-sculpture",
  name: "Sand Sculpture",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Compacted grains, crisp trowel cuts.",
  marketingCopy: "Reimagine your portrait in sculpted sand—compacted grain texture, sharp trowel cuts, and windswept coastal shading.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 150,
  assets: {
    thumbnail: "/art-style-thumbnails/sand-sculpture.jpg",
    thumbnailWebp: "/art-style-thumbnails/sand-sculpture.webp",
    thumbnailAvif: "/art-style-thumbnails/sand-sculpture.avif",
    preview: "/art-style-thumbnails/sand-sculpture.jpg",
    previewWebp: "/art-style-thumbnails/sand-sculpture.webp",
    previewAvif: "/art-style-thumbnails/sand-sculpture.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 50,
    prompt: "Recreate the exact image as a compacted sand sculpture—grainy, sunlit, and ephemeral. Preserve structure and silhouette; model forms with crisp trowel cuts, layered compaction strata, and slightly crumbly edges. Use warm beach sand color with varied grain size and dry vs. damp patches; add wind-swept micro ripples and tiny shell fragments sparingly. Stage on a sandy plinth with soft footprints/tool marks; bright outdoor light with sharp cast shadows.",
    updatedAt: "2025-10-30 22:23:10.809495+00",
  },
  story: null,
}
];

export const TONE_STYLES_BY_ID = new Map(TONE_STYLES.map((s) => [s.id, s]));
