// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run `npm run build:registry` to regenerate.

import type { StyleRegistryEntry } from '../types';

export const TONE_STYLES: StyleRegistryEntry[] = [
{
  id: "watercolor-dreams",
  slug: "watercolor-dreams",
  name: "Watercolor Dreams",
  tone: "signature",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Expressive watercolor with joyful drips.",
  marketingCopy: "Bring Your portrait to life with movement—loose washes, vivid splashes, and fluid blends.",
  badges: ["signature"],
  sortOrder: 20,
  assets: {
    thumbnail: "/art-style-thumbnails/watercolor-dreams.jpg",
    thumbnailWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    thumbnailAvif: "/art-style-thumbnails/watercolor-dreams.avif",
    preview: "/art-style-thumbnails/watercolor-dreams.jpg",
    previewWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    previewAvif: "/art-style-thumbnails/watercolor-dreams.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 4,
    prompt: "Recreate the exact image in an expressive watercolor style — bold, dynamic, and emotionally vibrant. Preserve the full composition and structure of the subject, including the subject's pose, features, proportions, and spatial arrangement. Use loose, energetic brushwork, vivid splashes of color, and spontaneous paint drips to convey movement and feeling. Let pigments flow and merge unpredictably, creating a painterly abstraction around the subject without distorting the core details. Emphasize contrast, texture, and fluid transitions, with a sense of joyful chaos that enhances — not overwhelms — the subject's presence. The result should feel alive and impressionistic, yet true to the original image.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Watercolor Dreams",
      "paragraph": "Watercolor Dreams channels expressive wash painting—loose, energetic strokes, vivid splashes, and spontaneous drips that let pigments mingle in motion.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Creative • Playful • Spontaneous",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Bedrooms • Entryways • Bright Kitchens",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Spontaneous drips and splashes",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "wc-mist-blue",
        "hex": "#9EC5E6",
        "label": "Mist Blue",
        "descriptor": "Cooling sky wash"
      },
      {
        "id": "wc-opera-rose",
        "hex": "#F58CAA",
        "label": "Opera Rose",
        "descriptor": "Vibrant splash note"
      },
      {
        "id": "wc-sun-ochre",
        "hex": "#E8C07A",
        "label": "Sun Ochre",
        "descriptor": "Warm paper glow"
      }
    ],
    "complementary": {
      "premium": "gallery-acrylic",
      "fallback": "fauve-splash"
    }
  },
},
{
  id: "colored-pencil",
  slug: "colored-pencil",
  name: "Colored Pencil",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Layered strokes with paper tooth.",
  marketingCopy: "Build rich depth with layered colored pencil strokes, delicate hatchwork, and pressed highlights.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/colored-pencil.jpg",
    thumbnailWebp: "/art-style-thumbnails/colored-pencil.webp",
    thumbnailAvif: "/art-style-thumbnails/colored-pencil.avif",
    preview: "/art-style-thumbnails/colored-pencil.jpg",
    previewWebp: "/art-style-thumbnails/colored-pencil.webp",
    previewAvif: "/art-style-thumbnails/colored-pencil.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 38,
    prompt: "Recreate the exact image as a colored pencil illustration — layered, precise, and richly textured. Preserve the full composition and structure of the subject with accurate proportions and clear silhouette. Build form using controlled hatching and cross-hatching, then deepen color with layered glazing and selective burnishing for smooth highlights. The result should feel detailed and handcrafted — a vibrant colored-pencil rendering that stays true to the original photo.",
    updatedAt: "2025-10-30 17:01:11.820672+00",
  },
  story: null,
},
{
  id: "memphis-pop",
  slug: "memphis-pop",
  name: "Memphis Pop",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Playful geometry, electric color.",
  marketingCopy: "Channel bold 80s energy with Memphis-inspired geometry, pattern punches, and high-voltage color.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/memphis-pop.jpg",
    thumbnailWebp: "/art-style-thumbnails/memphis-pop.webp",
    thumbnailAvif: "/art-style-thumbnails/memphis-pop.avif",
    preview: "/art-style-thumbnails/memphis-pop.jpg",
    previewWebp: "/art-style-thumbnails/memphis-pop.webp",
    previewAvif: "/art-style-thumbnails/memphis-pop.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 39,
    prompt: "Recreate the exact image in a Memphis design pop style — playful, geometric, and high-energy. Preserve the full structure of the subject with accurate proportions and a clean silhouette. Use flat, opaque color planes with crisp black keylines and limited halftone fills. Surround with ’80s motifs (squiggles, dots, checker, zigzags, circles/triangles) arranged on loose grid panels. Palette-lock to six colors: turquoise, lilac, peach, canary, black, white (no extra hues). Keep a clean buffer around face and hands (no patterns crossing features). Favor large, simple background blocks with a few pattern zones for rhythm. No gradients, painterly textures, or photographic shading. The result should feel bright, collectible, and instantly Memphis.",
    updatedAt: "2025-10-30 17:02:27.536618+00",
  },
  story: null,
},
{
  id: "liquid-chrome",
  slug: "liquid-chrome",
  name: "Liquid Chrome",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Mercury sheen, stretched highlights.",
  marketingCopy: "Wrap every contour in fluid metal with reflective chrome gradients and studio-grade specular beams.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 130,
  assets: {
    thumbnail: "/art-style-thumbnails/liquid-chrome.jpg",
    thumbnailWebp: "/art-style-thumbnails/liquid-chrome.webp",
    thumbnailAvif: "/art-style-thumbnails/liquid-chrome.avif",
    preview: "/art-style-thumbnails/liquid-chrome.jpg",
    previewWebp: "/art-style-thumbnails/liquid-chrome.webp",
    previewAvif: "/art-style-thumbnails/liquid-chrome.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 40,
    prompt: "Recreate the exact image as a liquid-chrome smear—glossy, mirrorlike, and sculptural. Preserve proportions and silhouette. Convert forms into high-gloss metallic surfaces; smear normals along graceful flow lines to elongate highlights. Use bright specular streaks and deep blacks; minimal midtones. Keep eyes readable via controlled highlight shapes; avoid melting features beyond recognition. Background is dark and uncluttered with faint reflection/caustic hints; no colored tints unless subtle cyan/steel accents.",
    updatedAt: "2025-10-30 17:06:26.949228+00",
  },
  story: null,
},
{
  id: "glass-ripple",
  slug: "glass-ripple",
  name: "Glass Ripple",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Refractive panes with bright rims.",
  marketingCopy: "Refract portraits through layered glass panes, luminous rim lights, and iridescent ripple caustics.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 140,
  assets: {
    thumbnail: "/art-style-thumbnails/glass-ripple.jpg",
    thumbnailWebp: "/art-style-thumbnails/glass-ripple.webp",
    thumbnailAvif: "/art-style-thumbnails/glass-ripple.avif",
    preview: "/art-style-thumbnails/glass-ripple.jpg",
    previewWebp: "/art-style-thumbnails/glass-ripple.webp",
    previewAvif: "/art-style-thumbnails/glass-ripple.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 41,
    prompt: "Recreate the exact image as refractive ripple glass—sleek, prismatic, and sculptural. Preserve proportions and silhouette. Convert surfaces into clear glass panels with normals derived from soft noise; bend and duplicate features subtly through refraction. Add bright specular rims and clean caustic streaks; apply a slight RGB misregister (1–2 px) for chromatic dispersion. Background remains dark to mid, with faint reflected streaks; glow is minimal.",
    updatedAt: "2025-10-30 17:07:29.908011+00",
  },
  story: null,
},
{
  id: "deco-royale",
  slug: "deco-royale",
  name: "Deco Royale",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Stepped geometry, luxe metallics.",
  marketingCopy: "Crown your subject with stepped Art Deco geometry, lacquered panels, and gilded metallic trims.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 150,
  assets: {
    thumbnail: "/art-style-thumbnails/deco-royale.jpg",
    thumbnailWebp: "/art-style-thumbnails/deco-royale.webp",
    thumbnailAvif: "/art-style-thumbnails/deco-royale.avif",
    preview: "/art-style-thumbnails/deco-royale.jpg",
    previewWebp: "/art-style-thumbnails/deco-royale.webp",
    previewAvif: "/art-style-thumbnails/deco-royale.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 15,
    prompt: "Recreate the exact image in a bold, modern Art Deco style — a dramatic fusion of classic glamour and contemporary edge. Maintain the subject's full composition, pose, and spatial layout with high fidelity. Apply rich, dimensional lighting and sharp, clean linework to create a sense of depth and visual focus. Use strong geometric framing, symmetry, and gold accents to echo iconic Deco architecture, balanced with smooth digital gradients and matte finishes. Emphasize a luxury palette — including deep teal, navy, black, gold, blush, and cream — for a sophisticated, high-impact aesthetic. The result should feel like a cinematic poster or luxury magazine cover: expressive, powerful, and timelessly stylish.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "the-renaissance",
  slug: "the-renaissance",
  name: "The Renaissance",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Old-master light, gilded accents.",
  marketingCopy: "Invoke old-master drama with layered oil glazes, chiaroscuro lighting, and gilded frame flourishes.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 160,
  assets: {
    thumbnail: "/art-style-thumbnails/the-renaissance.jpg",
    thumbnailWebp: "/art-style-thumbnails/the-renaissance.webp",
    thumbnailAvif: "/art-style-thumbnails/the-renaissance.avif",
    preview: "/art-style-thumbnails/the-renaissance.jpg",
    previewWebp: "/art-style-thumbnails/the-renaissance.webp",
    previewAvif: "/art-style-thumbnails/the-renaissance.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 42,
    prompt: "Recreate the exact image as a baroque/renaissance oil masterwork — rich chiaroscuro, velvety blacks, and tactile brushwork — enhanced with genuine gold-leaf ornament. Preserve the subject’s composition, pose, anatomy, and expression. Paint with layered glazes and controlled impasto; let warm candlelight model the face and hands. Add restrained gilding: garment trim, or frame cartouche that catches specular highlights and casts subtle gilt reflections onto nearby paint. Keep color harmonies in deep umbers, oxblood, ultramarine, and cream. The result should feel museum-caliber: dramatic, devotional, and exquisitely finished.",
    updatedAt: "2025-10-30 17:15:51.172479+00",
  },
  story: null,
},
{
  id: "sanctuary-glow",
  slug: "sanctuary-glow",
  name: "Sanctuary Glow",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Luminous stained-glass aura.",
  marketingCopy: "Cast ethereal stained-glass radiance with prismatic gradients, soft bloom, and cathedral halos.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 170,
  assets: {
    thumbnail: "/art-style-thumbnails/sanctuary-glow.jpg",
    thumbnailWebp: "/art-style-thumbnails/sanctuary-glow.webp",
    thumbnailAvif: "/art-style-thumbnails/sanctuary-glow.avif",
    preview: "/art-style-thumbnails/sanctuary-glow.jpg",
    previewWebp: "/art-style-thumbnails/sanctuary-glow.webp",
    previewAvif: "/art-style-thumbnails/sanctuary-glow.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 43,
    prompt: "Recreate the exact image as a luminous stained-glass window — leaded panes, jewel tones, and sunlit bloom. Preserve the subject’s pose, proportions, and facial readability while segmenting forms into glass panels bordered by realistic came (lead) lines. Use deep sapphire, ruby, emerald, and amber with faint seed bubbles and subtle internal gradients to simulate real glass. Introduce directional “cathedral” sunlight that passes through the panes, creating haloed edges, color spill, and soft caustic patterns on background surfaces. Keep detail micro-panes for eyes and hands; use larger panes for broader planes. The result should feel sacred and cinematic, as if the portrait were installed high in a grand nave.",
    updatedAt: "2025-10-30 17:17:20.746361+00",
  },
  story: null,
}
];

export const TONE_STYLES_BY_ID = new Map(TONE_STYLES.map((s) => [s.id, s]));
