// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run `npm run build:registry` to regenerate.

import type { StyleRegistryEntry } from '../types';

export const TONE_STYLES: StyleRegistryEntry[] = [
{
  id: "3d-storybook",
  slug: "3d-storybook",
  name: "3D Storybook",
  tone: "stylized",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Whimsical 3D illustrated style with storybook charm.",
  marketingCopy: "Bring characters to life with a whimsical 3D illustration finish.",
  badges: ["playful"],
  sortOrder: 40,
  assets: {
    thumbnail: "/art-style-thumbnails/3d-storybook.jpg",
    thumbnailWebp: "/art-style-thumbnails/3d-storybook.webp",
    thumbnailAvif: "/art-style-thumbnails/3d-storybook.avif",
    preview: "/art-style-thumbnails/3d-storybook.jpg",
    previewWebp: "/art-style-thumbnails/3d-storybook.webp",
    previewAvif: "/art-style-thumbnails/3d-storybook.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 7,
    prompt: "Recreate the exact image as a stylized 3D illustration — expressive, playful, and visually engaging. Preserve the full composition and structure of the original subject, including accurate shape, proportions, and spatial layout. Render the subject with smooth, rounded modeling, vibrant colors, and soft lighting to create a polished, animated look. Use exaggerated but intentional design elements to enhance personality and charm, whether the subject is a person, pet, vehicle, building, or object. The final image should feel joyful and dynamic, like a scene from a Pixar or Fortnite-style animated world — stylized yet true to the original form.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "90s-cartoon",
  slug: "90s-cartoon",
  name: "90s Cartoon",
  tone: "stylized",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Saturday-morning cartoon lines with flat cel shading and exaggerated poses.",
  marketingCopy: "Channel nostalgic 90s animation with thick outlines, two-step cel shading, and punchy weekend palettes.",
  badges: ["nostalgia"],
  sortOrder: 50,
  assets: {
    thumbnail: "/art-style-thumbnails/90s-cartoon.jpg",
    thumbnailWebp: "/art-style-thumbnails/90s-cartoon.webp",
    thumbnailAvif: "/art-style-thumbnails/90s-cartoon.avif",
    preview: "/art-style-thumbnails/90s-cartoon.jpg",
    previewWebp: "/art-style-thumbnails/90s-cartoon.webp",
    previewAvif: "/art-style-thumbnails/90s-cartoon.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 21,
    prompt: "Recreate the exact image as a 1990s TV cartoon. Preserve the full composition and structure of the subject. Translate forms into thick black keylines (3–6 px look), flat cel-shaded color blocks (1–2 shadow steps), and simple shape language (slightly exaggerated geometry, squash-and-stretch where natural). Use a vibrant Saturday-morning palette (teals, oranges, purples, limes) with minimal gradients; keep highlights as solid shapes, not soft glows. Background may use pattern panels (dots, zigzags, checker). The result should feel like a crisp, nostalgic 90s cartoon — playful, graphic, and instantly readable.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "pop-surrealism",
  slug: "pop-surrealism",
  name: "Pop Surrealism",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Hyperreal portraits drifting through dreamy, candy-colored surrealism.",
  marketingCopy: "Blend painterly realism with whimsical skies, glowing highlights, and fairytale emotion.",
  badges: ["dream"],
  requiredTier: "creator",
  sortOrder: 60,
  assets: {
    thumbnail: "/art-style-thumbnails/pop-surrealism.jpg",
    thumbnailWebp: "/art-style-thumbnails/pop-surrealism.webp",
    thumbnailAvif: "/art-style-thumbnails/pop-surrealism.avif",
    preview: "/art-style-thumbnails/pop-surrealism.jpg",
    previewWebp: "/art-style-thumbnails/pop-surrealism.webp",
    previewAvif: "/art-style-thumbnails/pop-surrealism.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 22,
    prompt: "Recreate the exact image in a vivid Pop Surrealism style — blending painterly realism with whimsical, dreamlike energy. Use richly saturated colors, hyperreal texture, and dramatic golden-hour lighting to enhance emotion. Incorporate fantastical, swirling skies and surreal background elements (like glowing clouds or floating orbs) that feel imaginative yet harmonious with the scene. The final artwork should evoke a fairytale-like quality — romantic, expressive, and elevated beyond reality — like a magical memory painted in vibrant, surreal detail.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "papercraft-layers",
  slug: "papercraft-layers",
  name: "Papercraft Layers",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Dimensional papercraft collage built from crisp cut shapes and soft shadows.",
  marketingCopy: "Stack handcrafted cardstock layers with precise edges, subtle bevels, and tactile drop shadows.",
  badges: ["crafted"],
  requiredTier: "creator",
  sortOrder: 70,
  assets: {
    thumbnail: "/art-style-thumbnails/papercraft.jpg",
    thumbnailWebp: "/art-style-thumbnails/papercraft.webp",
    thumbnailAvif: "/art-style-thumbnails/papercraft.avif",
    preview: "/art-style-thumbnails/papercraft.jpg",
    previewWebp: "/art-style-thumbnails/papercraft.webp",
    previewAvif: "/art-style-thumbnails/papercraft.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 23,
    prompt: "Recreate the exact image as a layered papercraft collage — dimensional, clean-edged, and softly shadowed. Preserve the full composition, pose, and proportions while decomposing the image into cut-paper shapes with precise vector-like edges. Stack 6–12 layers separated by subtle drop shadows and ambient occlusion to create depth. Use matte, slightly textured cardstock colors with tasteful gradients only where necessary. Keep eyes, hands, and key contours sharply defined. The result should feel like a premium handcrafted diorama made of paper.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "voxel-mineworld",
  slug: "voxel-mineworld",
  name: "Voxel Mineworld",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Chunky sandbox voxels rebuild portraits with crisp cubes and pixel textures.",
  marketingCopy: "Transform memories into playful voxel dioramas with clean silhouettes and ambient-lit cubes.",
  badges: ["voxel"],
  requiredTier: "creator",
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/voxel-mineworld.jpg",
    thumbnailWebp: "/art-style-thumbnails/voxel-mineworld.webp",
    thumbnailAvif: "/art-style-thumbnails/voxel-mineworld.avif",
    preview: "/art-style-thumbnails/voxel-mineworld.jpg",
    previewWebp: "/art-style-thumbnails/voxel-mineworld.webp",
    previewAvif: "/art-style-thumbnails/voxel-mineworld.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 24,
    prompt: "Recreate the exact image as a Minecraft-style voxel diorama. Preserve full composition and silhouette. Rebuild forms with hard cubic voxels (no bevels) at 2–8 px scale; use smaller voxels only for eyes/logos/hands. Apply matte, pixelated textures (no photo gradients), soft even lighting with ambient occlusion in creases, and a faint ground grid shadow. Keep silhouettes clean—no noisy fragmentation.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "claymation-sculpt",
  slug: "claymation-sculpt",
  name: "Claymation Sculpt",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Stop-motion clay portraiture with hand-molded texture and studio lighting.",
  marketingCopy: "Give portraits a tactile claymation finish with thumbprint detail, sculpted cuts, and warm tabletop light.",
  badges: ["whimsical"],
  requiredTier: "creator",
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/clay.jpg",
    thumbnailWebp: "/art-style-thumbnails/clay.webp",
    thumbnailAvif: "/art-style-thumbnails/clay.avif",
    preview: "/art-style-thumbnails/clay.jpg",
    previewWebp: "/art-style-thumbnails/clay.webp",
    previewAvif: "/art-style-thumbnails/clay.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 25,
    prompt: "Recreate the exact image as a stop-motion clay portrait — chunky, handmade, and charming. Preserve the subject’s full composition and proportions with a clean silhouette. Model forms as soft clay volumes with visible thumbprints, tool marks, and light seam lines; keep facial/details readable with sharper clay cuts. Use matte, saturated colors with subtle plasticine sheen; no photographic texture. Add tabletop studio lighting (soft key + tiny speculars) and a simple backdrop card. The result should feel like a frame from a claymation film — playful, tactile, and alive.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
}
];

export const TONE_STYLES_BY_ID = new Map(TONE_STYLES.map((s) => [s.id, s]));
