// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run `npm run build:registry` to regenerate.

import type { StyleRegistryEntry } from './types';

export const STYLE_REGISTRY: StyleRegistryEntry[] = [
{
  id: "original-image",
  slug: "original-image",
  name: "Original Image",
  tone: null,
  tier: "free",
  category: "original",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Your photo untouched - classic canvas print.",
  marketingCopy: "Keep it timeless with a faithful reproduction of your original photo.",
  badges: ["classic"],
  sortOrder: 0,
  assets: {
    thumbnail: "/art-style-thumbnails/original-image.jpg",
    thumbnailWebp: "/art-style-thumbnails/original-image.webp",
    thumbnailAvif: "/art-style-thumbnails/original-image.avif",
    preview: "/art-style-thumbnails/original-image.jpg",
    previewWebp: "/art-style-thumbnails/original-image.webp",
    previewAvif: "/art-style-thumbnails/original-image.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 1,
    prompt: "Keep the image exactly as is, no artistic transformation",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Classic Oil",
      "paragraph": "Classic Oil frames your portrait like a museum piece—rich pigments, heirloom brushwork, and softly lit warmth for timeless display.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Heirloom nostalgia",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Dining rooms · heritage walls",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Layered old-world brushstrokes",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "oil-amber",
        "hex": "#b37a3b",
        "label": "Heritage Amber",
        "descriptor": "Warms gallery lighting"
      },
      {
        "id": "oil-navy",
        "hex": "#1e2a44",
        "label": "Midnight Navy",
        "descriptor": "Anchors vintage contrast"
      },
      {
        "id": "oil-cream",
        "hex": "#f0ead6",
        "label": "Canvas Cream",
        "descriptor": "Softens skin tones"
      }
    ],
    "complementary": {
      "premium": "pastel-bliss",
      "fallback": "calm-watercolor"
    }
  },
},
{
  id: "classic-oil-painting",
  slug: "classic-oil-painting",
  name: "Classic Oil Painting",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Traditional oil painting texture with bold brush strokes.",
  marketingCopy: "Timeless elegance—refined brushwork, warm gallery light, and heirloom realism that honors every detail.",
  badges: ["classic"],
  sortOrder: 10,
  assets: {
    thumbnail: "/art-style-thumbnails/classic-oil-painting.jpg",
    thumbnailWebp: "/art-style-thumbnails/classic-oil-painting.webp",
    thumbnailAvif: "/art-style-thumbnails/classic-oil-painting.avif",
    preview: "/art-style-thumbnails/classic-oil-painting.jpg",
    previewWebp: "/art-style-thumbnails/classic-oil-painting.webp",
    previewAvif: "/art-style-thumbnails/classic-oil-painting.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 2,
    prompt: "Recreate the exact image as a majestic oil painting, evoking a sense of timeless elegance, with meticulous attention to detail and subtle texture, characteristic of traditional realism. Employ smooth, expressive brushstrokes that convey a sense of refinement, and a harmonious palette of natural tones, reminiscent of old masters. Soft, warm lighting casts a gentle glow on the subject, accentuating the subtle play of shadows and highlights. The composition is thoughtfully arranged, with a clear sense of balance and harmony, drawing the viewer's eye to the central figure. The subject's pose, facial features, and skin tone are meticulously preserved, with a focus on capturing the subtleties of expression, inviting the viewer to connect with the subject on a deeper level.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Classic Oil Painting",
      "paragraph": "Classic Oil frames your portrait like a museum piece—rich pigments, heirloom brushwork, and softly lit warmth for timeless display.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Timeless Elegance • Heirloom Nostalgia • Romantic Warmth • Classical Prestige",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Dining Spaces • Studies • Mantels • Living Rooms ",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Layered old-world brushstrokes, Glazed skin tones & selective impasto highlights",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "oil-amber",
        "hex": "#b37a3b",
        "label": "Heritage Amber",
        "descriptor": "Warms gallery lighting"
      },
      {
        "id": "oil-navy",
        "hex": "#1e2a44",
        "label": "Midnight Navy",
        "descriptor": "Anchors vintage contrast"
      },
      {
        "id": "oil-cream",
        "hex": "#f0ead6",
        "label": "Canvas Cream",
        "descriptor": "Softens skin tones"
      },
      {
        "id": "oil-umber",
        "hex": "#6B4B2A",
        "label": "Burnt Umber",
        "descriptor": "Old-master shadow base"
      }
    ],
    "complementary": {
      "premium": "the-renaissance",
      "fallback": "artisan-charcoal"
    }
  },
},
{
  id: "calm-watercolor",
  slug: "calm-watercolor",
  name: "Calm Watercolor",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Serene watercolor washes with gentle definition.",
  marketingCopy: "Paint tranquil portraits with feathered wet-on-wet washes, whispered vignettes, and poised simplicity.",
  badges: ["classic"],
  sortOrder: 20,
  assets: {
    thumbnail: "/art-style-thumbnails/calm-watercolor.jpg",
    thumbnailWebp: "/art-style-thumbnails/calm-watercolor.webp",
    thumbnailAvif: "/art-style-thumbnails/calm-watercolor.avif",
    preview: "/art-style-thumbnails/calm-watercolor.jpg",
    previewWebp: "/art-style-thumbnails/calm-watercolor.webp",
    previewAvif: "/art-style-thumbnails/calm-watercolor.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 20,
    prompt: "Recreate the exact image as a soft watercolor — quiet, luminous, and gently diffused. Preserve the full composition and structure of the subject with accurate proportions and clear focal details. Paint primarily wet-on-wet with feathered edges, letting shapes dissolve softly into surrounding washes. Avoid heavy splatter, harsh outlines, or dramatic blooms. Let backgrounds recede with atmospheric wash and a whispered vignette so the subject breathes in open space. The result should feel still, balanced, and tender — a tranquil watercolor that honors the original image with poised simplicity.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Calm Watercolor",
      "paragraph": "Watercolor Dreams bathes your memory in feathered washes and airy light leaks—gentle enough for bedrooms, expressive enough for your feed.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Serene Daydream • Quiet Optimism • Mindful Stillness",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Reading Nook • Hallways • Bedrooms • Gift Prints",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Wet-on-wet blends • Feathered edges & blooms • Soft vignette",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "wc-sea-glass",
        "hex": "#A9D3CF",
        "label": "Sea Glass",
        "descriptor": "Cooling calm"
      },
      {
        "id": "wc-warm-sand",
        "hex": "#EAD9C6",
        "label": "Warm Sand",
        "descriptor": "Soft earth balance"
      },
      {
        "id": "wc-mist",
        "hex": "#e8eef3",
        "label": "Cloud Mist",
        "descriptor": "Adds dreamy negative space"
      }
    ],
    "complementary": {
      "premium": "pastel-bliss",
      "fallback": "sumi-ink-whisper"
    }
  },
},
{
  id: "gallery-acrylic",
  slug: "gallery-acrylic",
  name: "Gallery Acrylic",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Rich acrylic layering with bold gallery brushwork and depth.",
  marketingCopy: "Layer bold acrylic strokes for a gallery-ready canvas packed with depth.",
  badges: ["classic"],
  sortOrder: 25,
  assets: {
    thumbnail: "/art-style-thumbnails/gallery-acrylic.jpg",
    thumbnailWebp: "/art-style-thumbnails/gallery-acrylic.webp",
    thumbnailAvif: "/art-style-thumbnails/gallery-acrylic.avif",
    preview: "/art-style-thumbnails/gallery-acrylic.jpg",
    previewWebp: "/art-style-thumbnails/gallery-acrylic.webp",
    previewAvif: "/art-style-thumbnails/gallery-acrylic.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 14,
    prompt: "Recreate the exact image as a contemporary acrylic painting — bold color, crisp edges, and clean, layered flats. Preserve the subject’s full composition. Render forms with decisive brush and palette-knife strokes; build color in opaque layers (lights over darks) with minimal glazing. Keep transitions intentional: hard edges on graphic planes and tighter details; soft, feathered edges only where needed for depth. Use a modern, saturated palette with high local contrast; avoid oil-style glow or muddy blends. Add subtle canvas tooth and occasional knife ridges to suggest fast-drying acrylic texture. The result should feel fresh, vivid, and gallery-ready — a sharp, modern staple that stays true to the original photo.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Gallery Acrylic",
      "paragraph": "Gallery Acrylic builds your image with confident strokes, stacked color layers, and gel-medium depth. Edges stay crisp where needed, glazing adds luminous blends elsewhere.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Modern Confidence • Vibrant Energy • Creative Momentum",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Statement Piece • Bedrooms • Living Rooms • Studios",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Clean graphic edges against soft blends, Layered glazing over crisp planes",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "acrylic-cobalt",
        "hex": "#2B6CB0",
        "label": "Cobalt Blue",
        "descriptor": "Cool depth layer"
      },
      {
        "id": "acrylic-cad-yellow",
        "hex": "#D88A1A",
        "label": "Cadmium Yellow Deep",
        "descriptor": "Warm energy field"
      },
      {
        "id": "acrylic-titanium",
        "hex": "#F4F3EF",
        "label": "Titanium White",
        "descriptor": "Sheen and lift"
      }
    ],
    "complementary": {
      "premium": "watercolor-dreams",
      "fallback": "street-graffiti"
    }
  },
},
{
  id: "watercolor-dreams",
  slug: "watercolor-dreams",
  name: "Watercolor Dreams",
  tone: "signature",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Expressive watercolor with joyful drips.",
  marketingCopy: "Bring Your portrait to life with movement—loose washes, vivid splashes, and fluid blends.",
  badges: ["signature"],
  sortOrder: 20,
  assets: {
    thumbnail: "/art-style-thumbnails/watercolor-dreams.jpg",
    thumbnailWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    thumbnailAvif: "/art-style-thumbnails/watercolor-dreams.avif",
    preview: "/art-style-thumbnails/watercolor-dreams.jpg",
    previewWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    previewAvif: "/art-style-thumbnails/watercolor-dreams.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 4,
    prompt: "Recreate the exact image in an expressive watercolor style — bold, dynamic, and emotionally vibrant. Preserve the full composition and structure of the subject, including the subject's pose, features, proportions, and spatial arrangement. Use loose, energetic brushwork, vivid splashes of color, and spontaneous paint drips to convey movement and feeling. Let pigments flow and merge unpredictably, creating a painterly abstraction around the subject without distorting the core details. Emphasize contrast, texture, and fluid transitions, with a sense of joyful chaos that enhances — not overwhelms — the subject's presence. The result should feel alive and impressionistic, yet true to the original image.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Watercolor Dreams",
      "paragraph": "Watercolor Dreams channels expressive wash painting—loose, energetic strokes, vivid splashes, and spontaneous drips that let pigments mingle in motion.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Creative • Playful • Spontaneous",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Bedrooms • Entryways • Bright Kitchens",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Spontaneous drips and splashes",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "wc-mist-blue",
        "hex": "#9EC5E6",
        "label": "Mist Blue",
        "descriptor": "Cooling sky wash"
      },
      {
        "id": "wc-opera-rose",
        "hex": "#F58CAA",
        "label": "Opera Rose",
        "descriptor": "Vibrant splash note"
      },
      {
        "id": "wc-sun-ochre",
        "hex": "#E8C07A",
        "label": "Sun Ochre",
        "descriptor": "Warm paper glow"
      }
    ],
    "complementary": {
      "premium": "gallery-acrylic",
      "fallback": "fauve-splash"
    }
  },
},
{
  id: "pastel-bliss",
  slug: "pastel-bliss",
  name: "Pastel Bliss",
  tone: "classic",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Airy soft-pastel blends with velvety gradients.",
  marketingCopy: "A hush of color—powdery pastels, feathered blends, and morning-light warmth for calm, elegant portraits.",
  badges: ["soft"],
  requiredTier: "creator",
  sortOrder: 30,
  assets: {
    thumbnail: "/art-style-thumbnails/pastel-bliss.jpg",
    thumbnailWebp: "/art-style-thumbnails/pastel-bliss.webp",
    thumbnailAvif: "/art-style-thumbnails/pastel-bliss.avif",
    preview: "/art-style-thumbnails/pastel-bliss.jpg",
    previewWebp: "/art-style-thumbnails/pastel-bliss.webp",
    previewAvif: "/art-style-thumbnails/pastel-bliss.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 5,
    prompt: "Recreate the exact image in a soft pastel illustration style — calming and emotionally warm, with clearly defined forms and balanced contrast. Preserve the full composition and subject structure, including accurate pose, features, proportions, and spatial layout. Use smooth shading and subtle blending between gentle pastel hues — but ensure the subject remains crisp and well-defined against the background. Avoid overly washed-out or faded tones; instead, apply light colors with intention and depth, creating a soft yet vibrant rendering. The final image should feel peaceful and nostalgic, while still vivid and visually engaging.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Pastel Bliss",
      "paragraph": "Pastel Bliss soothes with soft pastels, tactile grain, and morning-light warmth—ideal for cozy retreats and calming spaces.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Weightless Calm • Cozy Serenity • Gentle Romance • Dreamy Nostalgia",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Bedrooms • Offices • Kitchens • Bathrooms",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Velvet pastel gradients, Feathered edge blends, Lifted highlights & gentle haze",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "pastel-rose",
        "hex": "#f8cbd6",
        "label": "Petal Rose",
        "descriptor": "Softens portraits"
      },
      {
        "id": "pastel-mint",
        "hex": "#c8eddc",
        "label": "Mint Haze",
        "descriptor": "Calms the palette"
      },
      {
        "id": "pastel-cream",
        "hex": "#fdf2e9",
        "label": "Sunrise Cream",
        "descriptor": "Adds daylight warmth"
      }
    ],
    "complementary": {
      "premium": "calm-watercolor",
      "fallback": "classic-crayon"
    }
  },
},
{
  id: "pop-art-bust",
  slug: "pop-art-bust",
  name: "Pop Art Bust",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Bold pop art bust portraits with graphic halftones and sculpted contrast.",
  marketingCopy: "Deliver gallery-ready bust portraits with saturated halftones and punchy graphic shading.",
  badges: ["bold"],
  sortOrder: 40,
  assets: {
    thumbnail: "/art-style-thumbnails/pop-art.jpg",
    thumbnailWebp: "/art-style-thumbnails/pop-art.webp",
    thumbnailAvif: "/art-style-thumbnails/pop-art.avif",
    preview: "/art-style-thumbnails/pop-art.jpg",
    previewWebp: "/art-style-thumbnails/pop-art.webp",
    previewAvif: "/art-style-thumbnails/pop-art.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Neon Splash",
      "paragraph": "Neon Splash explodes with electric motion—UV drips, kinetic streaks, and stage-worthy glow that turns any capture into nightlife art.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Electric adrenaline",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Game rooms · celebration walls",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Neon paint trails with UV bloom",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "neon-magenta",
        "hex": "#ff2eb7",
        "label": "UV Magenta",
        "descriptor": "Injects night-life energy"
      },
      {
        "id": "neon-cyan",
        "hex": "#19d4ff",
        "label": "Electric Cyan",
        "descriptor": "Slices through the dark"
      },
      {
        "id": "neon-amber",
        "hex": "#ffb428",
        "label": "Pulse Amber",
        "descriptor": "Adds kinetic accents"
      }
    ],
    "complementary": {
      "premium": "electric-drip",
      "fallback": "pop-art-bust"
    }
  },
},
{
  id: "modern-colorblock",
  slug: "modern-colorblock",
  name: "Modern Colorblock",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Hard-edged color planes with poster-like negative space and crisp balance.",
  marketingCopy: "Compose gallery-ready portraits from pure color blocks, confident geometry, and modern negative space.",
  badges: ["modern"],
  sortOrder: 50,
  assets: {
    thumbnail: "/art-style-thumbnails/modern-colorblock.jpg",
    thumbnailWebp: "/art-style-thumbnails/modern-colorblock.webp",
    thumbnailAvif: "/art-style-thumbnails/modern-colorblock.avif",
    preview: "/art-style-thumbnails/modern-colorblock.jpg",
    previewWebp: "/art-style-thumbnails/modern-colorblock.webp",
    previewAvif: "/art-style-thumbnails/modern-colorblock.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 3,
    prompt: "Recreate the exact image in a modern colorblock style — bold, clean, and hard-edged. Preserve the full composition and structure of the subject with accurate proportions. Simplify surfaces into large, opaque color planes with razor-sharp edges; reserve small, high-contrast blocks for facial details and key accents. Build shadows and highlights as discrete blocks rather than soft fades; maintain generous negative space for a poster-like feel. The result should feel fresh, graphic, and gallery-ready — a confident modern portrait built from pure color shapes.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "dot-symphony",
  slug: "dot-symphony",
  name: "Dot Symphony",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Pointillist portraits rendered from luminous dot constellations and vibrating color.",
  marketingCopy: "Weave thousands of radiant dots into shimmering pointillist portraits that stay true to every contour.",
  badges: ["artful"],
  sortOrder: 60,
  assets: {
    thumbnail: "/art-style-thumbnails/dot-symphony.jpg",
    thumbnailWebp: "/art-style-thumbnails/dot-symphony.webp",
    thumbnailAvif: "/art-style-thumbnails/dot-symphony.avif",
    preview: "/art-style-thumbnails/dot-symphony.jpg",
    previewWebp: "/art-style-thumbnails/dot-symphony.webp",
    previewAvif: "/art-style-thumbnails/dot-symphony.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 19,
    prompt: "Recreate the exact image in an authentic pointillist style — built from countless small dots of pure color. Preserve the subject’s full composition, pose, proportions, and facial structure. Render form with closely packed dots that optically blend at viewing distance; avoid soft airbrush or continuous-tone gradients. Use luminous complements to model light and shadow. Keep edges readable by tightening dot density along contours and features. The result should feel radiant and shimmering, like a sunlit scene resolved through color vibration.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "fauve-splash",
  slug: "fauve-splash",
  name: "Fauve Splash",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Fauvist color bursts with liberated brushwork and joyful tonal exaggeration.",
  marketingCopy: "Channel fearless Fauve energy with high-key palettes, confident strokes, and exuberant emotion.",
  badges: ["expressive"],
  sortOrder: 70,
  assets: {
    thumbnail: "/art-style-thumbnails/deco-luxe.jpg",
    thumbnailWebp: "/art-style-thumbnails/deco-luxe.webp",
    thumbnailAvif: "/art-style-thumbnails/deco-luxe.avif",
    preview: "/art-style-thumbnails/deco-luxe.jpg",
    previewWebp: "/art-style-thumbnails/deco-luxe.webp",
    previewAvif: "/art-style-thumbnails/deco-luxe.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 18,
    prompt: "Recreate the exact image in a Fauvist style — wild color, bold shapes, and liberated brushwork. Preserve the subject’s composition, pose, and anatomy while simplifying forms into decisive planes. Replace natural hues with expressive, high-key color. Keep linework confident, contours slightly exaggerated, and lighting stylized rather than realistic. The result should feel joyful, daring, and saturated with emotion.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "hex-weave",
  slug: "hex-weave",
  name: "Hex Weave",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Interlocking hexagonal tessellations with soft gradients and woven light.",
  marketingCopy: "Wrap your portrait in geometric weaving—honeycomb planes, gleaming threads, and luminous negative space.",
  badges: ["abstract"],
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/hex-weave.jpg",
    thumbnailWebp: "/art-style-thumbnails/hex-weave.webp",
    thumbnailAvif: "/art-style-thumbnails/hex-weave.avif",
    preview: "/art-style-thumbnails/hex-weave.jpg",
    previewWebp: "/art-style-thumbnails/hex-weave.webp",
    previewAvif: "/art-style-thumbnails/hex-weave.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 29,
    prompt: "Recreate the exact image as an isometric hex weave—textile, dimensional, and readable. Preserve the subject’s full composition and a clean silhouette. Implement over/under weaving logic with subtle cast shadows. Increase strand density around eyes and lips for detail; use larger, looser weave on hair and background. Render strands with soft fiber sheen (matte to satin), avoiding photographic texture. Keep pupils and key features partially un-woven for identity; palette stays tasteful with one accent color thread.",
    updatedAt: "2025-10-30 03:26:58.086611+00",
  },
  story: null,
},
{
  id: "prisma-tesla",
  slug: "prisma-tesla",
  name: "Prisma Tesla",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Electro-spectrum prisms and field lines bending portrait contours.",
  marketingCopy: "Charge your art with neon prismatic flares, kinetic filaments, and energized negative space.",
  badges: ["abstract"],
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/prisma-tesla.jpg",
    thumbnailWebp: "/art-style-thumbnails/prisma-tesla.webp",
    thumbnailAvif: "/art-style-thumbnails/prisma-tesla.avif",
    preview: "/art-style-thumbnails/prisma-tesla.jpg",
    previewWebp: "/art-style-thumbnails/prisma-tesla.webp",
    previewAvif: "/art-style-thumbnails/prisma-tesla.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 30,
    prompt: "Recreate the exact image as a low-poly prism composition—faceted, crisp, and high-impact. Preserve full structure and pose. Triangulate forms with Delaunay-like facets; use finer facets around eyes and mouth, larger facets elsewhere. Assign each triangle a cohesive color ramp with mild hue shift; add slim bevel highlights on key edges, no heavy outlines. Introduce a few spectral light leaks near specular zones; keep skin tones stylized but believable. Background is dark-to-mid with soft bokeh sparkles; no facet overdraw on pupils.",
    updatedAt: "2025-10-30 03:27:34.727397+00",
  },
  story: null,
},
{
  id: "op-art-pulse",
  slug: "op-art-pulse",
  name: "Op Art Pulse",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Hypnotic moiré bands and vibrating contrasts with portrait silhouettes.",
  marketingCopy: "Spin optical rhythms around your subject—pulsing wave grids, stark monochrome beats, and kinetic energy.",
  badges: ["abstract"],
  sortOrder: 100,
  assets: {
    thumbnail: "/art-style-thumbnails/op-art-pulse.jpg",
    thumbnailWebp: "/art-style-thumbnails/op-art-pulse.webp",
    thumbnailAvif: "/art-style-thumbnails/op-art-pulse.avif",
    preview: "/art-style-thumbnails/op-art-pulse.jpg",
    previewWebp: "/art-style-thumbnails/op-art-pulse.webp",
    previewAvif: "/art-style-thumbnails/op-art-pulse.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 31,
    prompt: "Recreate the exact image in an optical art style — rhythmic, high-contrast patterns that create vibration and depth. Use a restrained palette (black/white or limited duotone) and control line frequency so features remain readable. Employ gradient line spacing to model volume and a subtle background field that pulses outward from the silhouette. The result should feel kinetic and mesmerizing — a crisp optical illusion that still honors the subject’s identity.",
    updatedAt: "2025-10-30 03:28:33.633157+00",
  },
  story: null,
},
{
  id: "street-graffiti",
  slug: "street-graffiti",
  name: "Street Graffiti",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Layered street stencil treatment with bold contrast and urban grit.",
  marketingCopy: "Hit city walls with crisp stencils, overspray halos, and concrete texture that make portraits pop.",
  badges: ["urban"],
  sortOrder: 95,
  assets: {
    thumbnail: "/art-style-thumbnails/street-graffiti.jpg",
    thumbnailWebp: "/art-style-thumbnails/street-graffiti.webp",
    thumbnailAvif: "/art-style-thumbnails/street-graffiti.avif",
    preview: "/art-style-thumbnails/street-graffiti.jpg",
    previewWebp: "/art-style-thumbnails/street-graffiti.webp",
    previewAvif: "/art-style-thumbnails/street-graffiti.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 26,
    prompt: "Recreate the exact image as a multi-layer street stencil — bold, high-contrast, and urban. Preserve the full composition and structure of the subject with accurate proportions and a clean silhouette. Reduce forms to 2–4 flat stencil layers (shadow, mid, light, highlight) with crisp cut edges and visible overspray halos. Place on a subtle wall texture (concrete, brick, plywood) with light paint bleed; keep facial/details sharp via tighter inner cuts. The result should feel like a hand-cut stencil hit cleanly on a city wall.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "riso-punch",
  slug: "riso-punch",
  name: "Riso Punch",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Risograph spot inks with tactile grain, layered screens, and playful misregistration.",
  marketingCopy: "Deliver punchy risograph posters with fluorescent inks, halftone grit, and energetic off-register overlays.",
  badges: ["print"],
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/riso-punch.jpg",
    thumbnailWebp: "/art-style-thumbnails/riso-punch.webp",
    thumbnailAvif: "/art-style-thumbnails/riso-punch.avif",
    preview: "/art-style-thumbnails/riso-punch.jpg",
    previewWebp: "/art-style-thumbnails/riso-punch.webp",
    previewAvif: "/art-style-thumbnails/riso-punch.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 17,
    prompt: "Recreate the exact image in a risograph print style — graphic, tactile, and slightly misregistered. Preserve the subject’s full composition, pose, proportions, and facial details while translating forms into bold shapes. Use a 2–3 color ink set (e.g., fluorescent pink, teal, sunflower yellow) with visible halftone textures, overprint blends, and subtle off-register edges for energy. Keep shadows as dot fields and midtones as layered screens; avoid photographic gradients. Paper texture should read as uncoated stock with light grain. The final image should feel like a studio poster print — punchy, imperfect, and irresistibly modern.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "3d-storybook",
  slug: "3d-storybook",
  name: "3D Storybook",
  tone: "stylized",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Whimsical 3D illustrated style with storybook charm.",
  marketingCopy: "Bring characters to life with a whimsical 3D illustration finish.",
  badges: ["playful"],
  sortOrder: 40,
  assets: {
    thumbnail: "/art-style-thumbnails/3d-storybook.jpg",
    thumbnailWebp: "/art-style-thumbnails/3d-storybook.webp",
    thumbnailAvif: "/art-style-thumbnails/3d-storybook.avif",
    preview: "/art-style-thumbnails/3d-storybook.jpg",
    previewWebp: "/art-style-thumbnails/3d-storybook.webp",
    previewAvif: "/art-style-thumbnails/3d-storybook.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 7,
    prompt: "Recreate the exact image as a stylized 3D illustration — expressive, playful, and visually engaging. Preserve the full composition and structure of the original subject, including accurate shape, proportions, and spatial layout. Render the subject with smooth, rounded modeling, vibrant colors, and soft lighting to create a polished, animated look. Use exaggerated but intentional design elements to enhance personality and charm, whether the subject is a person, pet, vehicle, building, or object. The final image should feel joyful and dynamic, like a scene from a Pixar or Fortnite-style animated world — stylized yet true to the original form.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "90s-cartoon",
  slug: "90s-cartoon",
  name: "90s Cartoon",
  tone: "stylized",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Saturday-morning cartoon lines with flat cel shading and exaggerated poses.",
  marketingCopy: "Channel nostalgic 90s animation with thick outlines, two-step cel shading, and punchy weekend palettes.",
  badges: ["nostalgia"],
  sortOrder: 50,
  assets: {
    thumbnail: "/art-style-thumbnails/90s-cartoon.jpg",
    thumbnailWebp: "/art-style-thumbnails/90s-cartoon.webp",
    thumbnailAvif: "/art-style-thumbnails/90s-cartoon.avif",
    preview: "/art-style-thumbnails/90s-cartoon.jpg",
    previewWebp: "/art-style-thumbnails/90s-cartoon.webp",
    previewAvif: "/art-style-thumbnails/90s-cartoon.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 21,
    prompt: "Recreate the exact image as a 1990s TV cartoon. Preserve the full composition and structure of the subject. Translate forms into thick black keylines (3–6 px look), flat cel-shaded color blocks (1–2 shadow steps), and simple shape language (slightly exaggerated geometry, squash-and-stretch where natural). Use a vibrant Saturday-morning palette (teals, oranges, purples, limes) with minimal gradients; keep highlights as solid shapes, not soft glows. Background may use pattern panels (dots, zigzags, checker). The result should feel like a crisp, nostalgic 90s cartoon — playful, graphic, and instantly readable.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "pop-surrealism",
  slug: "pop-surrealism",
  name: "Pop Surrealism",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Hyperreal portraits drifting through dreamy, candy-colored surrealism.",
  marketingCopy: "Blend painterly realism with whimsical skies, glowing highlights, and fairytale emotion.",
  badges: ["dream"],
  requiredTier: "creator",
  sortOrder: 60,
  assets: {
    thumbnail: "/art-style-thumbnails/pop-surrealism.jpg",
    thumbnailWebp: "/art-style-thumbnails/pop-surrealism.webp",
    thumbnailAvif: "/art-style-thumbnails/pop-surrealism.avif",
    preview: "/art-style-thumbnails/pop-surrealism.jpg",
    previewWebp: "/art-style-thumbnails/pop-surrealism.webp",
    previewAvif: "/art-style-thumbnails/pop-surrealism.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 22,
    prompt: "Recreate the exact image in a vivid Pop Surrealism style — blending painterly realism with whimsical, dreamlike energy. Use richly saturated colors, hyperreal texture, and dramatic golden-hour lighting to enhance emotion. Incorporate fantastical, swirling skies and surreal background elements (like glowing clouds or floating orbs) that feel imaginative yet harmonious with the scene. The final artwork should evoke a fairytale-like quality — romantic, expressive, and elevated beyond reality — like a magical memory painted in vibrant, surreal detail.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "papercraft-layers",
  slug: "papercraft-layers",
  name: "Papercraft Layers",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Dimensional papercraft collage built from crisp cut shapes and soft shadows.",
  marketingCopy: "Stack handcrafted cardstock layers with precise edges, subtle bevels, and tactile drop shadows.",
  badges: ["crafted"],
  requiredTier: "creator",
  sortOrder: 70,
  assets: {
    thumbnail: "/art-style-thumbnails/papercraft.jpg",
    thumbnailWebp: "/art-style-thumbnails/papercraft.webp",
    thumbnailAvif: "/art-style-thumbnails/papercraft.avif",
    preview: "/art-style-thumbnails/papercraft.jpg",
    previewWebp: "/art-style-thumbnails/papercraft.webp",
    previewAvif: "/art-style-thumbnails/papercraft.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 23,
    prompt: "Recreate the exact image as a layered papercraft collage — dimensional, clean-edged, and softly shadowed. Preserve the full composition, pose, and proportions while decomposing the image into cut-paper shapes with precise vector-like edges. Stack 6–12 layers separated by subtle drop shadows and ambient occlusion to create depth. Use matte, slightly textured cardstock colors with tasteful gradients only where necessary. Keep eyes, hands, and key contours sharply defined. The result should feel like a premium handcrafted diorama made of paper.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "voxel-mineworld",
  slug: "voxel-mineworld",
  name: "Voxel Mineworld",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Chunky sandbox voxels rebuild portraits with crisp cubes and pixel textures.",
  marketingCopy: "Transform memories into playful voxel dioramas with clean silhouettes and ambient-lit cubes.",
  badges: ["voxel"],
  requiredTier: "creator",
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/voxel-mineworld.jpg",
    thumbnailWebp: "/art-style-thumbnails/voxel-mineworld.webp",
    thumbnailAvif: "/art-style-thumbnails/voxel-mineworld.avif",
    preview: "/art-style-thumbnails/voxel-mineworld.jpg",
    previewWebp: "/art-style-thumbnails/voxel-mineworld.webp",
    previewAvif: "/art-style-thumbnails/voxel-mineworld.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 24,
    prompt: "Recreate the exact image as a Minecraft-style voxel diorama. Preserve full composition and silhouette. Rebuild forms with hard cubic voxels (no bevels) at 2–8 px scale; use smaller voxels only for eyes/logos/hands. Apply matte, pixelated textures (no photo gradients), soft even lighting with ambient occlusion in creases, and a faint ground grid shadow. Keep silhouettes clean—no noisy fragmentation.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "claymation-sculpt",
  slug: "claymation-sculpt",
  name: "Claymation Sculpt",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Stop-motion clay portraiture with hand-molded texture and studio lighting.",
  marketingCopy: "Give portraits a tactile claymation finish with thumbprint detail, sculpted cuts, and warm tabletop light.",
  badges: ["whimsical"],
  requiredTier: "creator",
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/clay.jpg",
    thumbnailWebp: "/art-style-thumbnails/clay.webp",
    thumbnailAvif: "/art-style-thumbnails/clay.avif",
    preview: "/art-style-thumbnails/clay.jpg",
    previewWebp: "/art-style-thumbnails/clay.webp",
    previewAvif: "/art-style-thumbnails/clay.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 25,
    prompt: "Recreate the exact image as a stop-motion clay portrait — chunky, handmade, and charming. Preserve the subject’s full composition and proportions with a clean silhouette. Model forms as soft clay volumes with visible thumbprints, tool marks, and light seam lines; keep facial/details readable with sharper clay cuts. Use matte, saturated colors with subtle plasticine sheen; no photographic texture. Add tabletop studio lighting (soft key + tiny speculars) and a simple backdrop card. The result should feel like a frame from a claymation film — playful, tactile, and alive.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "artisan-charcoal",
  slug: "artisan-charcoal",
  name: "Artisan Charcoal",
  tone: "classic",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Hand-drawn charcoal artistry with dramatic shading.",
  marketingCopy: "Sculpt dramatic portraits with handcrafted charcoal shading.",
  badges: ["sketch"],
  requiredTier: "creator",
  sortOrder: 40,
  assets: {
    thumbnail: "/art-style-thumbnails/artisan-charcoal.jpg",
    thumbnailWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    thumbnailAvif: "/art-style-thumbnails/artisan-charcoal.avif",
    preview: "/art-style-thumbnails/artisan-charcoal.jpg",
    previewWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    previewAvif: "/art-style-thumbnails/artisan-charcoal.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 8,
    prompt: "Recreate the exact image as a detailed charcoal sketch — textured, hand-drawn, and expressive. Preserve the full structure and composition of the original subject, including accurate proportions, angles, and spatial arrangement. Use rich crosshatching, soft smudging, and tonal shading to build form and depth, mimicking traditional charcoal on textured paper. Keep the subject's details clear and intact while rendering them in a warm, monochromatic palette. The result should feel timeless and handcrafted, like a finely rendered charcoal illustration that blends realism with artistic character.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "classic-crayon",
  slug: "classic-crayon",
  name: "Classic Crayon",
  tone: "classic",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Layered crayon strokes with nostalgic paper grain and hand-drawn warmth.",
  marketingCopy: "Blend soft waxy hues and storybook charm for a handcrafted crayon keepsake.",
  badges: ["classic"],
  requiredTier: "creator",
  sortOrder: 50,
  assets: {
    thumbnail: "/art-style-thumbnails/classic-crayon.jpg",
    thumbnailWebp: "/art-style-thumbnails/classic-crayon.webp",
    thumbnailAvif: "/art-style-thumbnails/classic-crayon.avif",
    preview: "/art-style-thumbnails/classic-crayon.jpg",
    previewWebp: "/art-style-thumbnails/classic-crayon.webp",
    previewAvif: "/art-style-thumbnails/classic-crayon.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 12,
    prompt: "Recreate the exact image as a hand-drawn crayon illustration — warm, waxy, and richly textured. Preserve the full composition and subject structure. Render forms with layered crayon strokes. Use a balanced color palette that matches the original image while allowing gentle artistic exaggeration; build shadows with cross-hatching and stacked complementary colors rather than flat black. The final image should read as a crisp, expressive crayon portrait — colorful, tactile, and true to the original photo.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "neon-splash",
  slug: "neon-splash",
  name: "Neon Splash",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Electric neon splashes with vibrant energy.",
  marketingCopy: "Ignite your portrait with neon streaks and kinetic color.",
  badges: ["neon"],
  sortOrder: 70,
  assets: {
    thumbnail: "/art-style-thumbnails/neon-splash.jpg",
    thumbnailWebp: "/art-style-thumbnails/neon-splash.webp",
    thumbnailAvif: "/art-style-thumbnails/neon-splash.avif",
    preview: "/art-style-thumbnails/neon-splash.jpg",
    previewWebp: "/art-style-thumbnails/neon-splash.webp",
    previewAvif: "/art-style-thumbnails/neon-splash.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 10,
    prompt: "Recreate the exact image in a dynamic Neon Splash style — electric, expressive, and bursting with high-intensity energy. Preserve the full subject composition, pose, and proportions with accurate facial features and visual structure. Surround the scene with vivid neon paint splashes, glowing outlines, and abstract light trails that radiate from the subject. Use a high-contrast color palette with hot pinks, electric blues, purples, and glowing oranges. Incorporate kinetic strokes, scatter effects, and surreal lighting to convey movement and emotion. The final image should feel like a glowing explosion of joy, power, and motion — where color and light collide in a captivating, artistic storm",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: {
    "narrative": {
      "headline": "The Story Behind Neon Splash",
      "paragraph": "Neon Splash explodes with electric motion—UV drips, kinetic streaks, and stage-worthy glow that turns any capture into nightlife art.",
      "bullets": [
        {
          "label": "Emotion",
          "value": "Electric adrenaline",
          "icon": "sparkle"
        },
        {
          "label": "Perfect for",
          "value": "Game rooms · celebration walls",
          "icon": "home"
        },
        {
          "label": "Signature detail",
          "value": "Neon paint trails with UV bloom",
          "icon": "brush"
        }
      ]
    },
    "palette": [
      {
        "id": "neon-magenta",
        "hex": "#ff2eb7",
        "label": "UV Magenta",
        "descriptor": "Injects night-life energy"
      },
      {
        "id": "neon-cyan",
        "hex": "#19d4ff",
        "label": "Electric Cyan",
        "descriptor": "Slices through the dark"
      },
      {
        "id": "neon-amber",
        "hex": "#ffb428",
        "label": "Pulse Amber",
        "descriptor": "Adds kinetic accents"
      }
    ],
    "complementary": {
      "premium": "electric-drip",
      "fallback": "pop-art-bust"
    }
  },
},
{
  id: "electric-drip",
  slug: "electric-drip",
  name: "Electric Drip",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Fluorescent paint pours cascading into neon bloom and kinetic splatter.",
  marketingCopy: "Coat your portraits in liquid neon drips, gravity streaks, and UV rim light energy.",
  badges: ["neon"],
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/electric-drip.jpg",
    thumbnailWebp: "/art-style-thumbnails/electric-drip.webp",
    thumbnailAvif: "/art-style-thumbnails/electric-drip.avif",
    preview: "/art-style-thumbnails/electric-drip.jpg",
    previewWebp: "/art-style-thumbnails/electric-drip.webp",
    previewAvif: "/art-style-thumbnails/electric-drip.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 11,
    prompt: "Recreate the exact image as a UV-neon drip/splatter painting. Preserve the full structure of the subject with a clean silhouette. Fluorescent accents: hot pink, electric blue, acid green, violet, and citrus orange. Build bold color fields, then layer sprays, splatter bursts, and gravity drips. Add soft neon bloom and thin rim-light glow along fast contours; use overspray speckle sparingly.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "glow-crayon",
  slug: "glow-crayon",
  name: "Glow Crayon",
  tone: "electric",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Hand-drawn neon wax strokes with blacklight glow and vibrant edge lighting.",
  marketingCopy: "Upgrade to neon wax crayon portraits with luminous outlines, iridescent shading, and studio pop.",
  badges: ["glow"],
  requiredTier: "creator",
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/glow-crayon.jpg",
    thumbnailWebp: "/art-style-thumbnails/glow-crayon.webp",
    thumbnailAvif: "/art-style-thumbnails/glow-crayon.avif",
    preview: "/art-style-thumbnails/glow-crayon.jpg",
    previewWebp: "/art-style-thumbnails/glow-crayon.webp",
    previewAvif: "/art-style-thumbnails/glow-crayon.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 27,
    prompt: "Recreate the exact image as a blacklight-inspired crayon illustration — bold, waxy, and nightlife-bright. Preserve the full composition, pose, proportions, and facial features. Build forms with thick crayon strokes and layered color stacks; use high-impact hues (hot pink, electric blue, acid green, violet) with a subtle outer glow to simulate UV pop. Keep edges outlined with confident dark marks; add cross-hatch shading and visible paper tooth for texture. Introduce selective white-crayon highlights and soft bloom around the brightest areas. The result should feel like a glow-party sketchbook page — playful, modern, and ultra shareable.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "casso-cubist",
  slug: "casso-cubist",
  name: "Casso Cubist",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Shattered planes, angular faceting, and gallery-grade cubist lighting.",
  marketingCopy: "Unlock cubist geometry—braided viewpoints, luxe palettes, and sculpted planes worthy of a salon wall.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/casso-cubist.jpg",
    thumbnailWebp: "/art-style-thumbnails/casso-cubist.webp",
    thumbnailAvif: "/art-style-thumbnails/casso-cubist.avif",
    preview: "/art-style-thumbnails/casso-cubist.jpg",
    previewWebp: "/art-style-thumbnails/casso-cubist.webp",
    previewAvif: "/art-style-thumbnails/casso-cubist.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 32,
    prompt: "Recreate the exact image in Synthetic Cubism — bold collage logic with graphic shapes and inserts. Preserve the composition and readable proportions of the subject, then rebuild forms using larger flat planes, cut-paper edges, and selective contour lines. Integrate collage elements (newsprint textures, music-staff scraps, woodgrain, painted labels) as surface inlays; keep them abstract and non-readable. Use a warmer, more playful palette (tan, cream, coral, olive, charcoal) with 1–2 accent colors. Outline only where needed; let overlapping shapes and stamped textures imply volume. The result should feel modern, witty, and constructed — a lively cubist collage that still honors the source image.",
    updatedAt: "2025-10-30 03:29:16.55469+00",
  },
  story: null,
},
{
  id: "sumi-ink-whisper",
  slug: "sumi-ink-whisper",
  name: "Sumi Ink Whisper",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Feathered ink washes and serene negative space with meditative linework.",
  marketingCopy: "Unlock tranquil sumi expression—floating washes, quiet gradients, and lyrical brush cadence.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/sumi-ink-whisper.jpg",
    thumbnailWebp: "/art-style-thumbnails/sumi-ink-whisper.webp",
    thumbnailAvif: "/art-style-thumbnails/sumi-ink-whisper.avif",
    preview: "/art-style-thumbnails/sumi-ink-whisper.jpg",
    previewWebp: "/art-style-thumbnails/sumi-ink-whisper.webp",
    previewAvif: "/art-style-thumbnails/sumi-ink-whisper.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 33,
    prompt: "Recreate the exact image as a sumi-ink marbling portrait—fluid, poetic, and atmospheric. Preserve composition and a clean silhouette. Reduce to a desaturated ink base, then advect soft marbling flows along cheek and hair contours; keep eyes, nostrils, and lip edges sharper for identity. Layer delicate gold-foil veins across broad ink pools; use feathered edges and paper grain. Avoid chaotic turbulence over the eye triangle. Add faint bloom around highlights; background remains a calm marbled wash.",
    updatedAt: "2025-10-30 03:30:08.333804+00",
  },
  story: null,
},
{
  id: "abstract-chorus",
  slug: "abstract-chorus",
  name: "Abstract Chorus",
  tone: "abstract",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Layered color harmonies with musical arcs and gestural echoes.",
  marketingCopy: "Unlock a chorus of color—syncopated arcs, lyrical gradients, and resonant painterly movement.",
  badges: ["abstract","premium"],
  requiredTier: "creator",
  sortOrder: 130,
  assets: {
    thumbnail: "/art-style-thumbnails/abstract-chorus.jpg",
    thumbnailWebp: "/art-style-thumbnails/abstract-chorus.webp",
    thumbnailAvif: "/art-style-thumbnails/abstract-chorus.avif",
    preview: "/art-style-thumbnails/abstract-chorus.jpg",
    previewWebp: "/art-style-thumbnails/abstract-chorus.webp",
    previewAvif: "/art-style-thumbnails/abstract-chorus.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 34,
    prompt: "Recreate the exact image as an Orphist color-harmony—prismatic, circular, and musical. Preserve overall structure and a clean silhouette. Build the background with translucent discs and curved arcs that radiate behind and around the silhouette. \\n",
    updatedAt: "2025-10-30 03:30:50.144199+00",
  },
  story: null,
},
{
  id: "voxel-arcade",
  slug: "voxel-arcade",
  name: "Voxel Arcade",
  tone: "electric",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Voxel portraits lit like arcade cabinets with neon bloom and pixel glow.",
  marketingCopy: "Unlock voxel arcade dioramas brimming with neon stripes, CRT bloom, and retro-futuristic energy.",
  badges: ["voxel"],
  requiredTier: "creator",
  sortOrder: 100,
  assets: {
    thumbnail: "/art-style-thumbnails/voxel-arcade.jpg",
    thumbnailWebp: "/art-style-thumbnails/voxel-arcade.webp",
    thumbnailAvif: "/art-style-thumbnails/voxel-arcade.avif",
    preview: "/art-style-thumbnails/voxel-arcade.jpg",
    previewWebp: "/art-style-thumbnails/voxel-arcade.webp",
    previewAvif: "/art-style-thumbnails/voxel-arcade.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 35,
    prompt: "Recreate the exact image in a neon cyber-voxel aesthetic — electric, high-contrast, and nightlife-ready. Preserve the subject’s composition, pose, and facial accuracy while reconstructing forms with dark matte voxels accented by emissive edges and light strips (cyan, magenta, violet). Add subtle scanlines, rim-light glows, and reflected color on nearby blocks; keep background voxels sparse to frame the figure. Maintain legibility by using finer voxel resolution at facial features and hands. The result should feel like a retro-future arcade hero shot — vibrant cubes lit by pure energy.",
    updatedAt: "2025-10-30 05:08:34.764196+00",
  },
  story: null,
},
{
  id: "retro-synthwave",
  slug: "retro-synthwave",
  name: "Retro Synthwave",
  tone: "electric",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Synthwave gradients, scanline glow, and retro-futuristic light trails.",
  marketingCopy: "Unlock premium synthwave portraits with sunset gradients, chromed highlights, and retro glitch energy.",
  badges: ["neon"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/retro-synthwave.jpg",
    thumbnailWebp: "/art-style-thumbnails/retro-synthwave.webp",
    thumbnailAvif: "/art-style-thumbnails/retro-synthwave.avif",
    preview: "/art-style-thumbnails/retro-synthwave.jpg",
    previewWebp: "/art-style-thumbnails/retro-synthwave.webp",
    previewAvif: "/art-style-thumbnails/retro-synthwave.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 37,
    prompt: "Recreate the exact image in a retro-future neon synthwave style — dark base, electric accents, and clean silhouette. Preserve the full composition and proportions of the subject. Palette-lock to hot magenta, electric cyan, violet, and indigo with small sunset orange/pink for glow accents; no naturalistic gradients.",
    updatedAt: "2025-10-30 05:14:50.092634+00",
  },
  story: null,
},
{
  id: "holowire-prism",
  slug: "holowire-prism",
  name: "Holowire Prism",
  tone: "electric",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Holographic wireframes refracted through neon prisms and chromatic bloom.",
  marketingCopy: "Unlock premium holowire portraits layered with radiant prisms, glitch refractions, and luminous haze.",
  badges: ["holo"],
  requiredTier: "creator",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/holowire-prism.jpg",
    thumbnailWebp: "/art-style-thumbnails/holowire-prism.webp",
    thumbnailAvif: "/art-style-thumbnails/holowire-prism.avif",
    preview: "/art-style-thumbnails/holowire-prism.jpg",
    previewWebp: "/art-style-thumbnails/holowire-prism.webp",
    previewAvif: "/art-style-thumbnails/holowire-prism.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 36,
    prompt: "Recreate the exact image as a neon wireframe overlay — precise, minimal, and high-contrast. Preserve proportions and a clean silhouette, then trace primary forms with thin emissive ribs (cyan/magenta/violet), using denser lines at joints and feature edges. Keep surfaces mostly matte; wireframe floats just above the subject with subtle parallax and a faint floor grid. Do not cross the pupils/emblems; let the wireframe conform around those features. Use mild neon bloom, no heavy glow; background remains dark and uncluttered.",
    updatedAt: "2025-10-30 05:12:33.691598+00",
  },
  story: null,
},
{
  id: "plush-figure",
  slug: "plush-figure",
  name: "Plush Figure",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Hand-sewn felt panels and cozy stitches.",
  marketingCopy: "Transform your portrait into a plush keepsake—hand-stitched felt seams, soft stuffing, and storybook charm.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/plush-figure.jpg",
    thumbnailWebp: "/art-style-thumbnails/plush-figure.webp",
    thumbnailAvif: "/art-style-thumbnails/plush-figure.avif",
    preview: "/art-style-thumbnails/plush-figure.jpg",
    previewWebp: "/art-style-thumbnails/plush-figure.webp",
    previewAvif: "/art-style-thumbnails/plush-figure.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 44,
    prompt: "Recreate the exact image as a hand-sewn felt plush—soft, stitched, and huggable. Preserve the subject’s composition and clean silhouette, then rebuild forms as layered felt panels with visible blanket stitches along edges, occasional cross-stitches, and tiny fabric seams. Use matte wool-fiber texture with light fuzz; add gentle poly-fill puffing for rounded volume. Replace eyes/emblems with button or embroidered details; no photographic surfaces. Keep colors cozy and slightly desaturated; add subtle fabric shadowing and tabletop studio light for depth.",
    updatedAt: "2025-10-30 22:19:21.165638+00",
  },
  story: null,
},
{
  id: "candy-gummy",
  slug: "candy-gummy",
  name: "Candy Gummy",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Translucent jelly glow with tiny bubbles.",
  marketingCopy: "Render your photo as a gummy treat—sparkling translucency, candy hues, and gleaming sugar bubbles suspended inside.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/candy-gummy.jpg",
    thumbnailWebp: "/art-style-thumbnails/candy-gummy.webp",
    thumbnailAvif: "/art-style-thumbnails/candy-gummy.avif",
    preview: "/art-style-thumbnails/candy-gummy.jpg",
    previewWebp: "/art-style-thumbnails/candy-gummy.webp",
    previewAvif: "/art-style-thumbnails/candy-gummy.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 45,
    prompt: "Recreate the exact image as a translucent gummy candy—edible, glossy, and playful. Preserve the silhouette and readable proportions; soften forms into rounded, jellylike geometry with subsurface glow. Render materials as tinted gelatin with tiny suspended air bubbles, smooth meniscus edges, and gentle stickiness; add specular highlights and soft internal caustics. Use a bright candy palette; optional “sugar sparkle” variant with fine crystalline dusting on outer surfaces. Background simple and clean to emphasize translucency.",
    updatedAt: "2025-10-30 22:19:43.914864+00",
  },
  story: null,
},
{
  id: "action-figure",
  slug: "action-figure",
  name: "Action Figure",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Poseable toy geometry with clean joints.",
  marketingCopy: "Strike a heroic pose—collector-grade plastic forms, snap-fit armor, and precise articulation points on every limb.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 100,
  assets: {
    thumbnail: "/art-style-thumbnails/action-figure.jpg",
    thumbnailWebp: "/art-style-thumbnails/action-figure.webp",
    thumbnailAvif: "/art-style-thumbnails/action-figure.avif",
    preview: "/art-style-thumbnails/action-figure.jpg",
    previewWebp: "/art-style-thumbnails/action-figure.webp",
    previewAvif: "/art-style-thumbnails/action-figure.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 46,
    prompt: "Recreate the exact image as an action figure—glossy PVC/ABS, collectible, and retail-ready. Preserve the subject’s composition and clean silhouette, then rebuild forms with panel breaks, visible injection-mold seams, and articulated joints (ball shoulders/hips, hinge elbows/knees, cut wrists/neck or equivalent connectors). Replace textures with crisp color blocking and tampo-printed decals; no photographic surfaces.",
    updatedAt: "2025-10-30 22:21:01.249607+00",
  },
  story: null,
},
{
  id: "porcelain-figurine",
  slug: "porcelain-figurine",
  name: "Porcelain Figurine",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Glazed ceramic shine with gold trim.",
  marketingCopy: "Elevate every detail with porcelain glaze, lustrous highlights, and hand-painted gold filigree worthy of a display cabinet.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/porcelain-figurine.jpg",
    thumbnailWebp: "/art-style-thumbnails/porcelain-figurine.webp",
    thumbnailAvif: "/art-style-thumbnails/porcelain-figurine.avif",
    preview: "/art-style-thumbnails/porcelain-figurine.jpg",
    previewWebp: "/art-style-thumbnails/porcelain-figurine.webp",
    previewAvif: "/art-style-thumbnails/porcelain-figurine.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 28,
    prompt: "Recreate the exact image as a porcelain figurine — high-gloss glaze, smooth sculpted planes, and hand-painted gold trim. Preserve the original pose and expression with refined, slightly idealized anatomy. Add delicate floral or filigree accents around clothing edges. Lighting should include bright highlights and subtle reflections characteristic of kiln-fired ceramic. Present on a small pedestal or tabletop shadow with a soft studio backdrop.",
    updatedAt: "2025-10-30T07:16:07.570425+00",
  },
  story: null,
},
{
  id: "ice-sculpture",
  slug: "ice-sculpture",
  name: "Ice Sculpture",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Chisel-cut crystal with frosty edges.",
  marketingCopy: "Carve your subject from crystal-clear ice—faceted planes, frosted edges, and refractive glow straight from a winter gala.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/ice-sculpture.jpg",
    thumbnailWebp: "/art-style-thumbnails/ice-sculpture.webp",
    thumbnailAvif: "/art-style-thumbnails/ice-sculpture.avif",
    preview: "/art-style-thumbnails/ice-sculpture.jpg",
    previewWebp: "/art-style-thumbnails/ice-sculpture.webp",
    previewAvif: "/art-style-thumbnails/ice-sculpture.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 47,
    prompt: "Recreate the exact image as a carved ice sculpture—crystalline, frosted, and event-ready. Preserve structure and silhouette; translate planes into chisel facets, bevels, and shallow relief cuts. Material: clear ice with internal cracks, faint bubbles, and edge frost; cooler blue-white rim light and subtle volumetric fog. Seat the piece on a pedestal or banquet plinth with a thin melt pool and soft reflections. Keep surfaces clean and glassy where freshly cut; heavier frost in shadowed recesses.",
    updatedAt: "2025-10-30 22:21:39.356445+00",
  },
  story: null,
},
{
  id: "bronze-statue",
  slug: "bronze-statue",
  name: "Bronze Statue",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Cast-metal patina on a plinth.",
  marketingCopy: "Celebrate timeless craftsmanship—cast bronze patina, engraved plinth, and gallery-ready museum lighting.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 130,
  assets: {
    thumbnail: "/art-style-thumbnails/bronze-statue.jpg",
    thumbnailWebp: "/art-style-thumbnails/bronze-statue.webp",
    thumbnailAvif: "/art-style-thumbnails/bronze-statue.avif",
    preview: "/art-style-thumbnails/bronze-statue.jpg",
    previewWebp: "/art-style-thumbnails/bronze-statue.webp",
    previewAvif: "/art-style-thumbnails/bronze-statue.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 48,
    prompt: "Recreate the exact image as a cast bronze statue—monumental, weighty, and timeless. Preserve overall structure and a clean silhouette; translate forms into metal with crisp chisel/tool detail and softened edges from casting. Render a dark bronze alloy with subtle patina (green/teal in recesses), warm speculars on highlights, and faint foundry seam hints; mount on a stone or plinth base with engraved plate. Keep surfaces matte-to-satin, no photographic texture; add gentle museum lighting with cool rim to reveal volume.",
    updatedAt: "2025-10-30 22:22:18.252698+00",
  },
  story: null,
},
{
  id: "wax-candle",
  slug: "wax-candle",
  name: "Wax Candle",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Translucent wax with wick and soft drips.",
  marketingCopy: "Melt into a luminous candle form—translucent wax, glowing core, and delicate drips descending toward the base.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 140,
  assets: {
    thumbnail: "/art-style-thumbnails/wax-candle.jpg",
    thumbnailWebp: "/art-style-thumbnails/wax-candle.webp",
    thumbnailAvif: "/art-style-thumbnails/wax-candle.avif",
    preview: "/art-style-thumbnails/wax-candle.jpg",
    previewWebp: "/art-style-thumbnails/wax-candle.webp",
    previewAvif: "/art-style-thumbnails/wax-candle.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 49,
    prompt: "Recreate the exact image as a sculpted wax candle—translucent, glossy, and gently melting. Preserve proportions and silhouette; simplify into smooth wax planes with subtle tool impressions, poured seams, and soft rounded edges. Material: tinted paraffin/beeswax with visible subsurface glow; include a centered wick and mild heat-softened sagging or drip trails. Optional lit variant with small flame, warm halo, and pooling wax at the base; place on a simple heat-safe dish.",
    updatedAt: "2025-10-30 22:22:43.041383+00",
  },
  story: null,
},
{
  id: "sand-sculpture",
  slug: "sand-sculpture",
  name: "Sand Sculpture",
  tone: "experimental",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Compacted grains, crisp trowel cuts.",
  marketingCopy: "Reimagine your portrait in sculpted sand—compacted grain texture, sharp trowel cuts, and windswept coastal shading.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 150,
  assets: {
    thumbnail: "/art-style-thumbnails/sand-sculpture.jpg",
    thumbnailWebp: "/art-style-thumbnails/sand-sculpture.webp",
    thumbnailAvif: "/art-style-thumbnails/sand-sculpture.avif",
    preview: "/art-style-thumbnails/sand-sculpture.jpg",
    previewWebp: "/art-style-thumbnails/sand-sculpture.webp",
    previewAvif: "/art-style-thumbnails/sand-sculpture.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 50,
    prompt: "Recreate the exact image as a compacted sand sculpture—grainy, sunlit, and ephemeral. Preserve structure and silhouette; model forms with crisp trowel cuts, layered compaction strata, and slightly crumbly edges. Use warm beach sand color with varied grain size and dry vs. damp patches; add wind-swept micro ripples and tiny shell fragments sparingly. Stage on a sandy plinth with soft footprints/tool marks; bright outdoor light with sharp cast shadows.",
    updatedAt: "2025-10-30 22:23:10.809495+00",
  },
  story: null,
},
{
  id: "colored-pencil",
  slug: "colored-pencil",
  name: "Colored Pencil",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Layered strokes with paper tooth.",
  marketingCopy: "Build rich depth with layered colored pencil strokes, delicate hatchwork, and pressed highlights.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/colored-pencil.jpg",
    thumbnailWebp: "/art-style-thumbnails/colored-pencil.webp",
    thumbnailAvif: "/art-style-thumbnails/colored-pencil.avif",
    preview: "/art-style-thumbnails/colored-pencil.jpg",
    previewWebp: "/art-style-thumbnails/colored-pencil.webp",
    previewAvif: "/art-style-thumbnails/colored-pencil.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 38,
    prompt: "Recreate the exact image as a colored pencil illustration — layered, precise, and richly textured. Preserve the full composition and structure of the subject with accurate proportions and clear silhouette. Build form using controlled hatching and cross-hatching, then deepen color with layered glazing and selective burnishing for smooth highlights. The result should feel detailed and handcrafted — a vibrant colored-pencil rendering that stays true to the original photo.",
    updatedAt: "2025-10-30 17:01:11.820672+00",
  },
  story: null,
},
{
  id: "memphis-pop",
  slug: "memphis-pop",
  name: "Memphis Pop",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Playful geometry, electric color.",
  marketingCopy: "Channel bold 80s energy with Memphis-inspired geometry, pattern punches, and high-voltage color.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/memphis-pop.jpg",
    thumbnailWebp: "/art-style-thumbnails/memphis-pop.webp",
    thumbnailAvif: "/art-style-thumbnails/memphis-pop.avif",
    preview: "/art-style-thumbnails/memphis-pop.jpg",
    previewWebp: "/art-style-thumbnails/memphis-pop.webp",
    previewAvif: "/art-style-thumbnails/memphis-pop.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 39,
    prompt: "Recreate the exact image in a Memphis design pop style — playful, geometric, and high-energy. Preserve the full structure of the subject with accurate proportions and a clean silhouette. Use flat, opaque color planes with crisp black keylines and limited halftone fills. Surround with ’80s motifs (squiggles, dots, checker, zigzags, circles/triangles) arranged on loose grid panels. Palette-lock to six colors: turquoise, lilac, peach, canary, black, white (no extra hues). Keep a clean buffer around face and hands (no patterns crossing features). Favor large, simple background blocks with a few pattern zones for rhythm. No gradients, painterly textures, or photographic shading. The result should feel bright, collectible, and instantly Memphis.",
    updatedAt: "2025-10-30 17:02:27.536618+00",
  },
  story: null,
},
{
  id: "liquid-chrome",
  slug: "liquid-chrome",
  name: "Liquid Chrome",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Mercury sheen, stretched highlights.",
  marketingCopy: "Wrap every contour in fluid metal with reflective chrome gradients and studio-grade specular beams.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 130,
  assets: {
    thumbnail: "/art-style-thumbnails/liquid-chrome.jpg",
    thumbnailWebp: "/art-style-thumbnails/liquid-chrome.webp",
    thumbnailAvif: "/art-style-thumbnails/liquid-chrome.avif",
    preview: "/art-style-thumbnails/liquid-chrome.jpg",
    previewWebp: "/art-style-thumbnails/liquid-chrome.webp",
    previewAvif: "/art-style-thumbnails/liquid-chrome.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 40,
    prompt: "Recreate the exact image as a liquid-chrome smear—glossy, mirrorlike, and sculptural. Preserve proportions and silhouette. Convert forms into high-gloss metallic surfaces; smear normals along graceful flow lines to elongate highlights. Use bright specular streaks and deep blacks; minimal midtones. Keep eyes readable via controlled highlight shapes; avoid melting features beyond recognition. Background is dark and uncluttered with faint reflection/caustic hints; no colored tints unless subtle cyan/steel accents.",
    updatedAt: "2025-10-30 17:06:26.949228+00",
  },
  story: null,
},
{
  id: "glass-ripple",
  slug: "glass-ripple",
  name: "Glass Ripple",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Refractive panes with bright rims.",
  marketingCopy: "Refract portraits through layered glass panes, luminous rim lights, and iridescent ripple caustics.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 140,
  assets: {
    thumbnail: "/art-style-thumbnails/glass-ripple.jpg",
    thumbnailWebp: "/art-style-thumbnails/glass-ripple.webp",
    thumbnailAvif: "/art-style-thumbnails/glass-ripple.avif",
    preview: "/art-style-thumbnails/glass-ripple.jpg",
    previewWebp: "/art-style-thumbnails/glass-ripple.webp",
    previewAvif: "/art-style-thumbnails/glass-ripple.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 41,
    prompt: "Recreate the exact image as refractive ripple glass—sleek, prismatic, and sculptural. Preserve proportions and silhouette. Convert surfaces into clear glass panels with normals derived from soft noise; bend and duplicate features subtly through refraction. Add bright specular rims and clean caustic streaks; apply a slight RGB misregister (1–2 px) for chromatic dispersion. Background remains dark to mid, with faint reflected streaks; glow is minimal.",
    updatedAt: "2025-10-30 17:07:29.908011+00",
  },
  story: null,
},
{
  id: "deco-royale",
  slug: "deco-royale",
  name: "Deco Royale",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Stepped geometry, luxe metallics.",
  marketingCopy: "Crown your subject with stepped Art Deco geometry, lacquered panels, and gilded metallic trims.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 150,
  assets: {
    thumbnail: "/art-style-thumbnails/deco-royale.jpg",
    thumbnailWebp: "/art-style-thumbnails/deco-royale.webp",
    thumbnailAvif: "/art-style-thumbnails/deco-royale.avif",
    preview: "/art-style-thumbnails/deco-royale.jpg",
    previewWebp: "/art-style-thumbnails/deco-royale.webp",
    previewAvif: "/art-style-thumbnails/deco-royale.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 15,
    prompt: "Recreate the exact image in a bold, modern Art Deco style — a dramatic fusion of classic glamour and contemporary edge. Maintain the subject's full composition, pose, and spatial layout with high fidelity. Apply rich, dimensional lighting and sharp, clean linework to create a sense of depth and visual focus. Use strong geometric framing, symmetry, and gold accents to echo iconic Deco architecture, balanced with smooth digital gradients and matte finishes. Emphasize a luxury palette — including deep teal, navy, black, gold, blush, and cream — for a sophisticated, high-impact aesthetic. The result should feel like a cinematic poster or luxury magazine cover: expressive, powerful, and timelessly stylish.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
  story: null,
},
{
  id: "the-renaissance",
  slug: "the-renaissance",
  name: "The Renaissance",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Old-master light, gilded accents.",
  marketingCopy: "Invoke old-master drama with layered oil glazes, chiaroscuro lighting, and gilded frame flourishes.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 160,
  assets: {
    thumbnail: "/art-style-thumbnails/the-renaissance.jpg",
    thumbnailWebp: "/art-style-thumbnails/the-renaissance.webp",
    thumbnailAvif: "/art-style-thumbnails/the-renaissance.avif",
    preview: "/art-style-thumbnails/the-renaissance.jpg",
    previewWebp: "/art-style-thumbnails/the-renaissance.webp",
    previewAvif: "/art-style-thumbnails/the-renaissance.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 42,
    prompt: "Recreate the exact image as a baroque/renaissance oil masterwork — rich chiaroscuro, velvety blacks, and tactile brushwork — enhanced with genuine gold-leaf ornament. Preserve the subject’s composition, pose, anatomy, and expression. Paint with layered glazes and controlled impasto; let warm candlelight model the face and hands. Add restrained gilding: garment trim, or frame cartouche that catches specular highlights and casts subtle gilt reflections onto nearby paint. Keep color harmonies in deep umbers, oxblood, ultramarine, and cream. The result should feel museum-caliber: dramatic, devotional, and exquisitely finished.",
    updatedAt: "2025-10-30 17:15:51.172479+00",
  },
  story: null,
},
{
  id: "sanctuary-glow",
  slug: "sanctuary-glow",
  name: "Sanctuary Glow",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Luminous stained-glass aura.",
  marketingCopy: "Cast ethereal stained-glass radiance with prismatic gradients, soft bloom, and cathedral halos.",
  badges: ["premium"],
  requiredTier: "creator",
  sortOrder: 170,
  assets: {
    thumbnail: "/art-style-thumbnails/sanctuary-glow.jpg",
    thumbnailWebp: "/art-style-thumbnails/sanctuary-glow.webp",
    thumbnailAvif: "/art-style-thumbnails/sanctuary-glow.avif",
    preview: "/art-style-thumbnails/sanctuary-glow.jpg",
    previewWebp: "/art-style-thumbnails/sanctuary-glow.webp",
    previewAvif: "/art-style-thumbnails/sanctuary-glow.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 43,
    prompt: "Recreate the exact image as a luminous stained-glass window — leaded panes, jewel tones, and sunlit bloom. Preserve the subject’s pose, proportions, and facial readability while segmenting forms into glass panels bordered by realistic came (lead) lines. Use deep sapphire, ruby, emerald, and amber with faint seed bubbles and subtle internal gradients to simulate real glass. Introduce directional “cathedral” sunlight that passes through the panes, creating haloed edges, color spill, and soft caustic patterns on background surfaces. Keep detail micro-panes for eyes and hands; use larger panes for broader planes. The result should feel sacred and cinematic, as if the portrait were installed high in a grand nave.",
    updatedAt: "2025-10-30 17:17:20.746361+00",
  },
  story: null,
}
];

export const STYLE_REGISTRY_BY_ID = new Map(STYLE_REGISTRY.map((style) => [style.id, style]));

export const STYLE_REGISTRY_BY_NUMERIC_ID = new Map(
  STYLE_REGISTRY.filter((style) => style.prompt).map((style) => [style.prompt!.numericId, style])
);
