// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run `npm run build:registry` to regenerate.

import type { StyleRegistryEntry } from './types';

export const STYLE_REGISTRY: StyleRegistryEntry[] = [
{
  id: "original-image",
  slug: "original-image",
  name: "Original Image",
  tone: null,
  tier: "free",
  category: "original",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Your photo untouched - classic canvas print.",
  marketingCopy: "Keep it timeless with a faithful reproduction of your original photo.",
  badges: ["classic"],
  sortOrder: 0,
  assets: {
    thumbnail: "/art-style-thumbnails/original-image.jpg",
    thumbnailWebp: "/art-style-thumbnails/original-image.webp",
    thumbnailAvif: "/art-style-thumbnails/original-image.avif",
    preview: "/art-style-thumbnails/original-image.jpg",
    previewWebp: "/art-style-thumbnails/original-image.webp",
    previewAvif: "/art-style-thumbnails/original-image.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 1,
    prompt: "Keep the image exactly as is, no artistic transformation",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "classic-oil-painting",
  slug: "classic-oil-painting",
  name: "Classic Oil Painting",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Traditional oil painting texture with bold brush strokes.",
  marketingCopy: "Channel the masters with rich brush strokes and museum-ready texture.",
  badges: ["classic"],
  sortOrder: 10,
  assets: {
    thumbnail: "/art-style-thumbnails/classic-oil-painting.jpg",
    thumbnailWebp: "/art-style-thumbnails/classic-oil-painting.webp",
    thumbnailAvif: "/art-style-thumbnails/classic-oil-painting.avif",
    preview: "/art-style-thumbnails/classic-oil-painting.jpg",
    previewWebp: "/art-style-thumbnails/classic-oil-painting.webp",
    previewAvif: "/art-style-thumbnails/classic-oil-painting.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 2,
    prompt: "Recreate the exact image as a majestic oil painting, evoking a sense of timeless elegance, with meticulous attention to detail and subtle texture, characteristic of traditional realism. Employ smooth, expressive brushstrokes that convey a sense of refinement, and a harmonious palette of natural tones, reminiscent of old masters. Soft, warm lighting casts a gentle glow on the subject, accentuating the subtle play of shadows and highlights. The composition is thoughtfully arranged, with a clear sense of balance and harmony, drawing the viewer's eye to the central figure. The subject's pose, facial features, and skin tone are meticulously preserved, with a focus on capturing the subtleties of expression, inviting the viewer to connect with the subject on a deeper level.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "watercolor-dreams",
  slug: "watercolor-dreams",
  name: "Watercolor Dreams",
  tone: "trending",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Soft washes with gentle light leaks perfect for portraits.",
  marketingCopy: "Give portraits a dreamy wash with soft watercolor gradients.",
  badges: ["trending"],
  sortOrder: 20,
  assets: {
    thumbnail: "/art-style-thumbnails/watercolor-dreams.jpg",
    thumbnailWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    thumbnailAvif: "/art-style-thumbnails/watercolor-dreams.avif",
    preview: "/art-style-thumbnails/watercolor-dreams.jpg",
    previewWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    previewAvif: "/art-style-thumbnails/watercolor-dreams.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 4,
    prompt: "Recreate the exact image in an expressive watercolor style — bold, dynamic, and emotionally vibrant. Preserve the full composition and structure of the subject, including the subject's pose, features, proportions, and spatial arrangement. Use loose, energetic brushwork, vivid splashes of color, and spontaneous paint drips to convey movement and feeling. Let pigments flow and merge unpredictably, creating a painterly abstraction around the subject without distorting the core details. Emphasize contrast, texture, and fluid transitions, with a sense of joyful chaos that enhances — not overwhelms — the subject's presence. The result should feel alive and impressionistic, yet true to the original image.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "pastel-bliss",
  slug: "pastel-bliss",
  name: "Pastel Bliss",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Gentle color washes with soft grain highlights.",
  marketingCopy: "Create calming canvases with airy pastels and gentle texture.",
  badges: ["soft"],
  sortOrder: 30,
  assets: {
    thumbnail: "/art-style-thumbnails/pastel-bliss.jpg",
    thumbnailWebp: "/art-style-thumbnails/pastel-bliss.webp",
    thumbnailAvif: "/art-style-thumbnails/pastel-bliss.avif",
    preview: "/art-style-thumbnails/pastel-bliss.jpg",
    previewWebp: "/art-style-thumbnails/pastel-bliss.webp",
    previewAvif: "/art-style-thumbnails/pastel-bliss.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 5,
    prompt: "Recreate the exact image in a soft pastel illustration style — calming and emotionally warm, with clearly defined forms and balanced contrast. Preserve the full composition and subject structure, including accurate pose, features, proportions, and spatial layout. Use smooth shading and subtle blending between gentle pastel hues — but ensure the subject remains crisp and well-defined against the background. Avoid overly washed-out or faded tones; instead, apply light colors with intention and depth, creating a soft yet vibrant rendering. The final image should feel peaceful and nostalgic, while still vivid and visually engaging.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "3d-storybook",
  slug: "3d-storybook",
  name: "3D Storybook",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Whimsical 3D illustrated style with storybook charm.",
  marketingCopy: "Bring characters to life with a whimsical 3D illustration finish.",
  badges: ["playful"],
  sortOrder: 40,
  assets: {
    thumbnail: "/art-style-thumbnails/3d-storybook.jpg",
    thumbnailWebp: "/art-style-thumbnails/3d-storybook.webp",
    thumbnailAvif: "/art-style-thumbnails/3d-storybook.avif",
    preview: "/art-style-thumbnails/3d-storybook.jpg",
    previewWebp: "/art-style-thumbnails/3d-storybook.webp",
    previewAvif: "/art-style-thumbnails/3d-storybook.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 7,
    prompt: "Recreate the exact image as a stylized 3D illustration — expressive, playful, and visually engaging. Preserve the full composition and structure of the original subject, including accurate shape, proportions, and spatial layout. Render the subject with smooth, rounded modeling, vibrant colors, and soft lighting to create a polished, animated look. Use exaggerated but intentional design elements to enhance personality and charm, whether the subject is a person, pet, vehicle, building, or object. The final image should feel joyful and dynamic, like a scene from a Pixar or Fortnite-style animated world — stylized yet true to the original form.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "pop-art-burst",
  slug: "pop-art-burst",
  name: "Pop Art Burst",
  tone: "stylized",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Bold Warhol-inspired pop art with vibrant colors.",
  marketingCopy: "Spin up high-energy canvases with comic book dots and punchy palettes.",
  badges: ["bold"],
  sortOrder: 50,
  assets: {
    thumbnail: "/art-style-thumbnails/pop-art-burst.jpg",
    thumbnailWebp: "/art-style-thumbnails/pop-art-burst.webp",
    thumbnailAvif: "/art-style-thumbnails/pop-art-burst.avif",
    preview: "/art-style-thumbnails/pop-art-burst.jpg",
    previewWebp: "/art-style-thumbnails/pop-art-burst.webp",
    previewAvif: "/art-style-thumbnails/pop-art-burst.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 9,
    prompt: "Recreate the exact image in a bold comic-style pop art illustration — inspired by vintage halftone printing and retro poster design. Maintain the full composition and subject structure, including accurate pose, proportions, facial features, and spatial layout. Apply thick black outlines, flat color blocking, and vibrant, saturated tones — especially reds, blues, and yellows — to create a high-impact graphic look. Use dense halftone dot textures to add visual rhythm and dimension across both subject and background. The final image should be energetic and expressive, while staying true to the subject's original form and mood, like a stylized moment frozen in a vintage comic book.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "artisan-charcoal",
  slug: "artisan-charcoal",
  name: "Artisan Charcoal",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Hand-drawn charcoal artistry with dramatic shading.",
  marketingCopy: "Sculpt dramatic portraits with handcrafted charcoal shading.",
  badges: ["sketch"],
  sortOrder: 60,
  assets: {
    thumbnail: "/art-style-thumbnails/artisan-charcoal.jpg",
    thumbnailWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    thumbnailAvif: "/art-style-thumbnails/artisan-charcoal.avif",
    preview: "/art-style-thumbnails/artisan-charcoal.jpg",
    previewWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    previewAvif: "/art-style-thumbnails/artisan-charcoal.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 8,
    prompt: "Recreate the exact image as a detailed charcoal sketch — textured, hand-drawn, and expressive. Preserve the full structure and composition of the original subject, including accurate proportions, angles, and spatial arrangement. Use rich crosshatching, soft smudging, and tonal shading to build form and depth, mimicking traditional charcoal on textured paper. Keep the subject's details clear and intact while rendering them in a warm, monochromatic palette. The result should feel timeless and handcrafted, like a finely rendered charcoal illustration that blends realism with artistic character.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "neon-splash",
  slug: "neon-splash",
  name: "Neon Splash",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Electric neon splashes with vibrant energy.",
  marketingCopy: "Ignite your portrait with neon streaks and kinetic color.",
  badges: ["neon"],
  sortOrder: 70,
  assets: {
    thumbnail: "/art-style-thumbnails/neon-splash.jpg",
    thumbnailWebp: "/art-style-thumbnails/neon-splash.webp",
    thumbnailAvif: "/art-style-thumbnails/neon-splash.avif",
    preview: "/art-style-thumbnails/neon-splash.jpg",
    previewWebp: "/art-style-thumbnails/neon-splash.webp",
    previewAvif: "/art-style-thumbnails/neon-splash.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 10,
    prompt: "Recreate the exact image in a dynamic Neon Splash style — electric, expressive, and bursting with high-intensity energy. Preserve the full subject composition, pose, and proportions with accurate facial features and visual structure. Surround the scene with vivid neon paint splashes, glowing outlines, and abstract light trails that radiate from the subject. Use a high-contrast color palette with hot pinks, electric blues, purples, and glowing oranges. Incorporate kinetic strokes, scatter effects, and surreal lighting to convey movement and emotion. The final image should feel like a glowing explosion of joy, power, and motion — where color and light collide in a captivating, artistic storm",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "electric-bloom",
  slug: "electric-bloom",
  name: "Electric Bloom",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Luminous bloom effects with electric color palettes.",
  marketingCopy: "Flood the canvas with vivid blooms and luminous lighting.",
  badges: ["glow"],
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/electric-bloom.jpg",
    thumbnailWebp: "/art-style-thumbnails/electric-bloom.webp",
    thumbnailAvif: "/art-style-thumbnails/electric-bloom.avif",
    preview: "/art-style-thumbnails/electric-bloom.jpg",
    previewWebp: "/art-style-thumbnails/electric-bloom.webp",
    previewAvif: "/art-style-thumbnails/electric-bloom.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 11,
    prompt: "Recreate this exact image as electric glow neon art — with the subject outlined in glowing lines, surrounded by radiant highlights and pulsing neon energy. Maintain the subject's exact pose, facial details, and composition, while enhancing it with bold contrast, vibrant lighting, and an expressive aura. Use high-energy light trails, edge-lit glow, and a mix of fluorescent and electric tones to evoke a sense of power and presence — like a vivid memory lit from within.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "deco-luxe",
  slug: "deco-luxe",
  name: "Deco Luxe",
  tone: "stylized",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Art Deco elegance with geometric luxury.",
  marketingCopy: "Frame your subjects with gilded Art Deco geometry and glam.",
  badges: ["luxury"],
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/deco-luxe.jpg",
    thumbnailWebp: "/art-style-thumbnails/deco-luxe.webp",
    thumbnailAvif: "/art-style-thumbnails/deco-luxe.avif",
    preview: "/art-style-thumbnails/deco-luxe.jpg",
    previewWebp: "/art-style-thumbnails/deco-luxe.webp",
    previewAvif: "/art-style-thumbnails/deco-luxe.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 15,
    prompt: "Recreate the exact image in a bold, modern Art Deco style — a dramatic fusion of classic glamour and contemporary edge. Maintain the subject's full composition, pose, and spatial layout with high fidelity. Apply rich, dimensional lighting and sharp, clean linework to create a sense of depth and visual focus. Use strong geometric framing, symmetry, and gold accents to echo iconic Deco architecture, balanced with smooth digital gradients and matte finishes. Emphasize a luxury palette — including deep teal, navy, black, gold, blush, and cream — for a sophisticated, high-impact aesthetic. The result should feel like a cinematic poster or luxury magazine cover: expressive, powerful, and timelessly stylish.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "abstract-fusion",
  slug: "abstract-fusion",
  name: "Abstract Fusion",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Bold geometric abstraction with luminous color blocking.",
  marketingCopy: "Blend geometry and color for energetic abstract compositions.",
  badges: ["modern"],
  sortOrder: 100,
  assets: {
    thumbnail: "/art-style-thumbnails/abstract-fusion.jpg",
    thumbnailWebp: "/art-style-thumbnails/abstract-fusion.webp",
    thumbnailAvif: "/art-style-thumbnails/abstract-fusion.avif",
    preview: "/art-style-thumbnails/abstract-fusion.jpg",
    previewWebp: "/art-style-thumbnails/abstract-fusion.webp",
    previewAvif: "/art-style-thumbnails/abstract-fusion.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 13,
    prompt: "Create abstract fusion art by blending watercolor, digital textures, and geometric patterns into a cohesive, expressive, multi-style composition. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "gemstone-poly",
  slug: "gemstone-poly",
  name: "Gemstone Poly",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Low-poly crystalline facets with gemstone brilliance.",
  marketingCopy: "Cut portraits into shimmering gemstone-inspired facets.",
  badges: ["facet"],
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/gemstone-poly.jpg",
    thumbnailWebp: "/art-style-thumbnails/gemstone-poly.webp",
    thumbnailAvif: "/art-style-thumbnails/gemstone-poly.avif",
    preview: "/art-style-thumbnails/gemstone-poly.jpg",
    previewWebp: "/art-style-thumbnails/gemstone-poly.webp",
    previewAvif: "/art-style-thumbnails/gemstone-poly.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 6,
    prompt: "Recreate the exact image as an artistic low poly illustration — colorful, faceted, and compositionally accurate. Preserve the full subject structure, including precise pose, facial features, proportions, and spatial layout. Break the image into angular geometric polygons of varied sizes, using bold color blocking and gradient transitions to reflect natural shading. Emphasize artistic abstraction through clean edges and stylized fragmentation, while maintaining visual clarity and realism in the subject. The result should feel modern and decorative — like a vibrant digital mosaic that's both expressive and true to the original form.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "signature-aurora",
  slug: "signature-aurora",
  name: "Aurora Signature",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 10,
  description: "Premium aurora gradients layered with hand-painted highlights.",
  marketingCopy: "Unlock Wondertone’s signature finish with luminous aurora light.",
  badges: ["exclusive","new"],
  requiredTier: "plus",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/signature-aurora.jpg",
    thumbnailWebp: null,
    thumbnailAvif: null,
    preview: "/art-style-thumbnails/signature-aurora.jpg",
    previewWebp: null,
    previewAvif: null,
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
}
];

export const STYLE_REGISTRY_BY_ID = new Map(STYLE_REGISTRY.map((style) => [style.id, style]));

export const STYLE_REGISTRY_BY_NUMERIC_ID = new Map(
  STYLE_REGISTRY.filter((style) => style.prompt).map((style) => [style.prompt!.numericId, style])
);
