// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run `npm run build:registry` to regenerate.

import type { StyleRegistryEntry } from './types';

export const STYLE_REGISTRY: StyleRegistryEntry[] = [
{
  id: "original-image",
  slug: "original-image",
  name: "Original Image",
  tone: null,
  tier: "free",
  category: "original",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Your photo untouched - classic canvas print.",
  marketingCopy: "Keep it timeless with a faithful reproduction of your original photo.",
  badges: ["classic"],
  sortOrder: 0,
  assets: {
    thumbnail: "/art-style-thumbnails/original-image.jpg",
    thumbnailWebp: "/art-style-thumbnails/original-image.webp",
    thumbnailAvif: "/art-style-thumbnails/original-image.avif",
    preview: "/art-style-thumbnails/original-image.jpg",
    previewWebp: "/art-style-thumbnails/original-image.webp",
    previewAvif: "/art-style-thumbnails/original-image.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 1,
    prompt: "Keep the image exactly as is, no artistic transformation",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "classic-oil-painting",
  slug: "classic-oil-painting",
  name: "Classic Oil Painting",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Traditional oil painting texture with bold brush strokes.",
  marketingCopy: "Channel the masters with rich brush strokes and museum-ready texture.",
  badges: ["classic"],
  sortOrder: 10,
  assets: {
    thumbnail: "/art-style-thumbnails/classic-oil-painting.jpg",
    thumbnailWebp: "/art-style-thumbnails/classic-oil-painting.webp",
    thumbnailAvif: "/art-style-thumbnails/classic-oil-painting.avif",
    preview: "/art-style-thumbnails/classic-oil-painting.jpg",
    previewWebp: "/art-style-thumbnails/classic-oil-painting.webp",
    previewAvif: "/art-style-thumbnails/classic-oil-painting.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 2,
    prompt: "Recreate the exact image as a majestic oil painting, evoking a sense of timeless elegance, with meticulous attention to detail and subtle texture, characteristic of traditional realism. Employ smooth, expressive brushstrokes that convey a sense of refinement, and a harmonious palette of natural tones, reminiscent of old masters. Soft, warm lighting casts a gentle glow on the subject, accentuating the subtle play of shadows and highlights. The composition is thoughtfully arranged, with a clear sense of balance and harmony, drawing the viewer's eye to the central figure. The subject's pose, facial features, and skin tone are meticulously preserved, with a focus on capturing the subtleties of expression, inviting the viewer to connect with the subject on a deeper level.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "calm-watercolor",
  slug: "calm-watercolor",
  name: "Calm Watercolor",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Quiet watercolor washes with soft edges, luminous gradients, and gentle definition.",
  marketingCopy: "Paint tranquil portraits with feathered wet-on-wet washes, whispered vignettes, and poised simplicity.",
  badges: ["classic"],
  sortOrder: 20,
  assets: {
    thumbnail: "/art-style-thumbnails/watercolor-dreams.jpg",
    thumbnailWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    thumbnailAvif: "/art-style-thumbnails/watercolor-dreams.avif",
    preview: "/art-style-thumbnails/watercolor-dreams.jpg",
    previewWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    previewAvif: "/art-style-thumbnails/watercolor-dreams.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 20,
    prompt: "Recreate the exact image as a soft watercolor — quiet, luminous, and gently diffused. Preserve the full composition and structure of the subject with accurate proportions and clear focal details. Paint primarily wet-on-wet with feathered edges, letting shapes dissolve softly into surrounding washes. Avoid heavy splatter, harsh outlines, or dramatic blooms. Let backgrounds recede with atmospheric wash and a whispered vignette so the subject breathes in open space. The result should feel still, balanced, and tender — a tranquil watercolor that honors the original image with poised simplicity.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "gallery-acrylic",
  slug: "gallery-acrylic",
  name: "Gallery Acrylic",
  tone: "classic",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Rich acrylic layering with bold gallery brushwork and depth.",
  marketingCopy: "Layer bold acrylic strokes for a gallery-ready canvas packed with depth.",
  badges: ["classic"],
  sortOrder: 25,
  assets: {
    thumbnail: "/art-style-thumbnails/classic-oil-painting.jpg",
    thumbnailWebp: "/art-style-thumbnails/classic-oil-painting.webp",
    thumbnailAvif: "/art-style-thumbnails/classic-oil-painting.avif",
    preview: "/art-style-thumbnails/classic-oil-painting.jpg",
    previewWebp: "/art-style-thumbnails/classic-oil-painting.webp",
    previewAvif: "/art-style-thumbnails/classic-oil-painting.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 14,
    prompt: "Recreate the exact image as a contemporary acrylic painting — bold color, crisp edges, and clean, layered flats. Preserve the subject’s full composition. Render forms with decisive brush and palette-knife strokes; build color in opaque layers (lights over darks) with minimal glazing. Keep transitions intentional: hard edges on graphic planes and tighter details; soft, feathered edges only where needed for depth. Use a modern, saturated palette with high local contrast; avoid oil-style glow or muddy blends. Add subtle canvas tooth and occasional knife ridges to suggest fast-drying acrylic texture. The result should feel fresh, vivid, and gallery-ready — a sharp, modern staple that stays true to the original photo.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "watercolor-dreams",
  slug: "watercolor-dreams",
  name: "Watercolor Dreams",
  tone: "trending",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Soft washes with gentle light leaks perfect for portraits.",
  marketingCopy: "Give portraits a dreamy wash with soft watercolor gradients.",
  badges: ["trending"],
  sortOrder: 20,
  assets: {
    thumbnail: "/art-style-thumbnails/watercolor-dreams.jpg",
    thumbnailWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    thumbnailAvif: "/art-style-thumbnails/watercolor-dreams.avif",
    preview: "/art-style-thumbnails/watercolor-dreams.jpg",
    previewWebp: "/art-style-thumbnails/watercolor-dreams.webp",
    previewAvif: "/art-style-thumbnails/watercolor-dreams.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 4,
    prompt: "Recreate the exact image in an expressive watercolor style — bold, dynamic, and emotionally vibrant. Preserve the full composition and structure of the subject, including the subject's pose, features, proportions, and spatial arrangement. Use loose, energetic brushwork, vivid splashes of color, and spontaneous paint drips to convey movement and feeling. Let pigments flow and merge unpredictably, creating a painterly abstraction around the subject without distorting the core details. Emphasize contrast, texture, and fluid transitions, with a sense of joyful chaos that enhances — not overwhelms — the subject's presence. The result should feel alive and impressionistic, yet true to the original image.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "pastel-bliss",
  slug: "pastel-bliss",
  name: "Pastel Bliss",
  tone: "classic",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Gentle color washes with soft grain highlights.",
  marketingCopy: "Create calming canvases with airy pastels and gentle texture.",
  badges: ["soft"],
  requiredTier: "creator",
  sortOrder: 30,
  assets: {
    thumbnail: "/art-style-thumbnails/pastel-bliss.jpg",
    thumbnailWebp: "/art-style-thumbnails/pastel-bliss.webp",
    thumbnailAvif: "/art-style-thumbnails/pastel-bliss.avif",
    preview: "/art-style-thumbnails/pastel-bliss.jpg",
    previewWebp: "/art-style-thumbnails/pastel-bliss.webp",
    previewAvif: "/art-style-thumbnails/pastel-bliss.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 5,
    prompt: "Recreate the exact image in a soft pastel illustration style — calming and emotionally warm, with clearly defined forms and balanced contrast. Preserve the full composition and subject structure, including accurate pose, features, proportions, and spatial layout. Use smooth shading and subtle blending between gentle pastel hues — but ensure the subject remains crisp and well-defined against the background. Avoid overly washed-out or faded tones; instead, apply light colors with intention and depth, creating a soft yet vibrant rendering. The final image should feel peaceful and nostalgic, while still vivid and visually engaging.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "pop-art-bust",
  slug: "pop-art-bust",
  name: "Pop Art Bust",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Bold pop art bust portraits with graphic halftones and sculpted contrast.",
  marketingCopy: "Deliver gallery-ready bust portraits with saturated halftones and punchy graphic shading.",
  badges: ["bold"],
  sortOrder: 40,
  assets: {
    thumbnail: "/art-style-thumbnails/pop-art-burst.jpg",
    thumbnailWebp: "/art-style-thumbnails/pop-art-burst.webp",
    thumbnailAvif: "/art-style-thumbnails/pop-art-burst.avif",
    preview: "/art-style-thumbnails/pop-art-burst.jpg",
    previewWebp: "/art-style-thumbnails/pop-art-burst.webp",
    previewAvif: "/art-style-thumbnails/pop-art-burst.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
},
{
  id: "modern-colorblock",
  slug: "modern-colorblock",
  name: "Modern Colorblock",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Hard-edged color planes with poster-like negative space and crisp balance.",
  marketingCopy: "Compose gallery-ready portraits from pure color blocks, confident geometry, and modern negative space.",
  badges: ["modern"],
  sortOrder: 50,
  assets: {
    thumbnail: "/art-style-thumbnails/abstract-fusion.jpg",
    thumbnailWebp: "/art-style-thumbnails/abstract-fusion.webp",
    thumbnailAvif: "/art-style-thumbnails/abstract-fusion.avif",
    preview: "/art-style-thumbnails/abstract-fusion.jpg",
    previewWebp: "/art-style-thumbnails/abstract-fusion.webp",
    previewAvif: "/art-style-thumbnails/abstract-fusion.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 3,
    prompt: "Recreate the exact image in a modern colorblock style — bold, clean, and hard-edged. Preserve the full composition and structure of the subject with accurate proportions. Simplify surfaces into large, opaque color planes with razor-sharp edges; reserve small, high-contrast blocks for facial details and key accents. Build shadows and highlights as discrete blocks rather than soft fades; maintain generous negative space for a poster-like feel. The result should feel fresh, graphic, and gallery-ready — a confident modern portrait built from pure color shapes.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "dot-symphony",
  slug: "dot-symphony",
  name: "Dot Symphony",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Pointillist portraits rendered from luminous dot constellations and vibrating color.",
  marketingCopy: "Weave thousands of radiant dots into shimmering pointillist portraits that stay true to every contour.",
  badges: ["artful"],
  sortOrder: 60,
  assets: {
    thumbnail: "/art-style-thumbnails/neon-splash.jpg",
    thumbnailWebp: "/art-style-thumbnails/neon-splash.webp",
    thumbnailAvif: "/art-style-thumbnails/neon-splash.avif",
    preview: "/art-style-thumbnails/neon-splash.jpg",
    previewWebp: "/art-style-thumbnails/neon-splash.webp",
    previewAvif: "/art-style-thumbnails/neon-splash.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 19,
    prompt: "Recreate the exact image in an authentic pointillist style — built from countless small dots of pure color. Preserve the subject’s full composition, pose, proportions, and facial structure. Render form with closely packed dots that optically blend at viewing distance; avoid soft airbrush or continuous-tone gradients. Use luminous complements to model light and shadow. Keep edges readable by tightening dot density along contours and features. The result should feel radiant and shimmering, like a sunlit scene resolved through color vibration.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "fauve-splash",
  slug: "fauve-splash",
  name: "Fauve Splash",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Fauvist color bursts with liberated brushwork and joyful tonal exaggeration.",
  marketingCopy: "Channel fearless Fauve energy with high-key palettes, confident strokes, and exuberant emotion.",
  badges: ["expressive"],
  sortOrder: 70,
  assets: {
    thumbnail: "/art-style-thumbnails/deco-luxe.jpg",
    thumbnailWebp: "/art-style-thumbnails/deco-luxe.webp",
    thumbnailAvif: "/art-style-thumbnails/deco-luxe.avif",
    preview: "/art-style-thumbnails/deco-luxe.jpg",
    previewWebp: "/art-style-thumbnails/deco-luxe.webp",
    previewAvif: "/art-style-thumbnails/deco-luxe.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 18,
    prompt: "Recreate the exact image in a Fauvist style — wild color, bold shapes, and liberated brushwork. Preserve the subject’s composition, pose, and anatomy while simplifying forms into decisive planes. Replace natural hues with expressive, high-key color. Keep linework confident, contours slightly exaggerated, and lighting stylized rather than realistic. The result should feel joyful, daring, and saturated with emotion.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "swiss-grid",
  slug: "swiss-grid",
  name: "Swiss Grid",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "International Typographic precision with modular grids and calm tonal planes.",
  marketingCopy: "Frame portraits on a disciplined Swiss grid—clean geometry, intentional whitespace, and refined minimalism.",
  badges: ["design"],
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/gemstone-poly.jpg",
    thumbnailWebp: "/art-style-thumbnails/gemstone-poly.webp",
    thumbnailAvif: "/art-style-thumbnails/gemstone-poly.avif",
    preview: "/art-style-thumbnails/gemstone-poly.jpg",
    previewWebp: "/art-style-thumbnails/gemstone-poly.webp",
    previewAvif: "/art-style-thumbnails/gemstone-poly.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 16,
    prompt: "Recreate the exact image in an International Typographic Style (Swiss Grid) — precise, minimal, and rigorously aligned. Preserve the full composition and structure of the subject with accurate proportions. Translate forms into clean, flat tonal planes and simple geometric shapes; use a strict underlying grid with consistent margins, modular spacing, and a visible baseline rhythm.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "street-graffiti",
  slug: "street-graffiti",
  name: "Street Graffiti",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Layered street stencil treatment with bold contrast and urban grit.",
  marketingCopy: "Hit city walls with crisp stencils, overspray halos, and concrete texture that make portraits pop.",
  badges: ["urban"],
  sortOrder: 95,
  assets: {
    thumbnail: "/art-style-thumbnails/artisan-charcoal.jpg",
    thumbnailWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    thumbnailAvif: "/art-style-thumbnails/artisan-charcoal.avif",
    preview: "/art-style-thumbnails/artisan-charcoal.jpg",
    previewWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    previewAvif: "/art-style-thumbnails/artisan-charcoal.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 26,
    prompt: "Recreate the exact image as a multi-layer street stencil — bold, high-contrast, and urban. Preserve the full composition and structure of the subject with accurate proportions and a clean silhouette. Reduce forms to 2–4 flat stencil layers (shadow, mid, light, highlight) with crisp cut edges and visible overspray halos. Place on a subtle wall texture (concrete, brick, plywood) with light paint bleed; keep facial/details sharp via tighter inner cuts. The result should feel like a hand-cut stencil hit cleanly on a city wall.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "riso-punch",
  slug: "riso-punch",
  name: "Riso Punch",
  tone: "modern",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Risograph spot inks with tactile grain, layered screens, and playful misregistration.",
  marketingCopy: "Deliver punchy risograph posters with fluorescent inks, halftone grit, and energetic off-register overlays.",
  badges: ["print"],
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/artisan-charcoal.jpg",
    thumbnailWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    thumbnailAvif: "/art-style-thumbnails/artisan-charcoal.avif",
    preview: "/art-style-thumbnails/artisan-charcoal.jpg",
    previewWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    previewAvif: "/art-style-thumbnails/artisan-charcoal.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 17,
    prompt: "Recreate the exact image in a risograph print style — graphic, tactile, and slightly misregistered. Preserve the subject’s full composition, pose, proportions, and facial details while translating forms into bold shapes. Use a 2–3 color ink set (e.g., fluorescent pink, teal, sunflower yellow) with visible halftone textures, overprint blends, and subtle off-register edges for energy. Keep shadows as dot fields and midtones as layered screens; avoid photographic gradients. Paper texture should read as uncoated stock with light grain. The final image should feel like a studio poster print — punchy, imperfect, and irresistibly modern.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "3d-storybook",
  slug: "3d-storybook",
  name: "3D Storybook",
  tone: "stylized",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Whimsical 3D illustrated style with storybook charm.",
  marketingCopy: "Bring characters to life with a whimsical 3D illustration finish.",
  badges: ["playful"],
  sortOrder: 40,
  assets: {
    thumbnail: "/art-style-thumbnails/3d-storybook.jpg",
    thumbnailWebp: "/art-style-thumbnails/3d-storybook.webp",
    thumbnailAvif: "/art-style-thumbnails/3d-storybook.avif",
    preview: "/art-style-thumbnails/3d-storybook.jpg",
    previewWebp: "/art-style-thumbnails/3d-storybook.webp",
    previewAvif: "/art-style-thumbnails/3d-storybook.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 7,
    prompt: "Recreate the exact image as a stylized 3D illustration — expressive, playful, and visually engaging. Preserve the full composition and structure of the original subject, including accurate shape, proportions, and spatial layout. Render the subject with smooth, rounded modeling, vibrant colors, and soft lighting to create a polished, animated look. Use exaggerated but intentional design elements to enhance personality and charm, whether the subject is a person, pet, vehicle, building, or object. The final image should feel joyful and dynamic, like a scene from a Pixar or Fortnite-style animated world — stylized yet true to the original form.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "90s-cartoon",
  slug: "90s-cartoon",
  name: "90s Cartoon",
  tone: "stylized",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Saturday-morning cartoon lines with flat cel shading and exaggerated poses.",
  marketingCopy: "Channel nostalgic 90s animation with thick outlines, two-step cel shading, and punchy weekend palettes.",
  badges: ["nostalgia"],
  sortOrder: 50,
  assets: {
    thumbnail: "/art-style-thumbnails/pop-art-burst.jpg",
    thumbnailWebp: "/art-style-thumbnails/pop-art-burst.webp",
    thumbnailAvif: "/art-style-thumbnails/pop-art-burst.avif",
    preview: "/art-style-thumbnails/pop-art-burst.jpg",
    previewWebp: "/art-style-thumbnails/pop-art-burst.webp",
    previewAvif: "/art-style-thumbnails/pop-art-burst.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 21,
    prompt: "Recreate the exact image as a 1990s TV cartoon. Preserve the full composition and structure of the subject. Translate forms into thick black keylines (3–6 px look), flat cel-shaded color blocks (1–2 shadow steps), and simple shape language (slightly exaggerated geometry, squash-and-stretch where natural). Use a vibrant Saturday-morning palette (teals, oranges, purples, limes) with minimal gradients; keep highlights as solid shapes, not soft glows. Background may use pattern panels (dots, zigzags, checker). The result should feel like a crisp, nostalgic 90s cartoon — playful, graphic, and instantly readable.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "pop-surrealism",
  slug: "pop-surrealism",
  name: "Pop Surrealism",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Hyperreal portraits drifting through dreamy, candy-colored surrealism.",
  marketingCopy: "Blend painterly realism with whimsical skies, glowing highlights, and fairytale emotion.",
  badges: ["dream"],
  requiredTier: "creator",
  sortOrder: 60,
  assets: {
    thumbnail: "/art-style-thumbnails/neon-splash.jpg",
    thumbnailWebp: "/art-style-thumbnails/neon-splash.webp",
    thumbnailAvif: "/art-style-thumbnails/neon-splash.avif",
    preview: "/art-style-thumbnails/neon-splash.jpg",
    previewWebp: "/art-style-thumbnails/neon-splash.webp",
    previewAvif: "/art-style-thumbnails/neon-splash.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 22,
    prompt: "Recreate the exact image in a vivid Pop Surrealism style — blending painterly realism with whimsical, dreamlike energy. Use richly saturated colors, hyperreal texture, and dramatic golden-hour lighting to enhance emotion. Incorporate fantastical, swirling skies and surreal background elements (like glowing clouds or floating orbs) that feel imaginative yet harmonious with the scene. The final artwork should evoke a fairytale-like quality — romantic, expressive, and elevated beyond reality — like a magical memory painted in vibrant, surreal detail.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "papercraft-layers",
  slug: "papercraft-layers",
  name: "Papercraft Layers",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Dimensional papercraft collage built from crisp cut shapes and soft shadows.",
  marketingCopy: "Stack handcrafted cardstock layers with precise edges, subtle bevels, and tactile drop shadows.",
  badges: ["crafted"],
  requiredTier: "creator",
  sortOrder: 70,
  assets: {
    thumbnail: "/art-style-thumbnails/abstract-fusion.jpg",
    thumbnailWebp: "/art-style-thumbnails/abstract-fusion.webp",
    thumbnailAvif: "/art-style-thumbnails/abstract-fusion.avif",
    preview: "/art-style-thumbnails/abstract-fusion.jpg",
    previewWebp: "/art-style-thumbnails/abstract-fusion.webp",
    previewAvif: "/art-style-thumbnails/abstract-fusion.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 23,
    prompt: "Recreate the exact image as a layered papercraft collage — dimensional, clean-edged, and softly shadowed. Preserve the full composition, pose, and proportions while decomposing the image into cut-paper shapes with precise vector-like edges. Stack 6–12 layers separated by subtle drop shadows and ambient occlusion to create depth. Use matte, slightly textured cardstock colors with tasteful gradients only where necessary. Keep eyes, hands, and key contours sharply defined. The result should feel like a premium handcrafted diorama made of paper.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "voxel-mineworld",
  slug: "voxel-mineworld",
  name: "Voxel Mineworld",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Chunky sandbox voxels rebuild portraits with crisp cubes and pixel textures.",
  marketingCopy: "Transform memories into playful voxel dioramas with clean silhouettes and ambient-lit cubes.",
  badges: ["voxel"],
  requiredTier: "creator",
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/gemstone-poly.jpg",
    thumbnailWebp: "/art-style-thumbnails/gemstone-poly.webp",
    thumbnailAvif: "/art-style-thumbnails/gemstone-poly.avif",
    preview: "/art-style-thumbnails/gemstone-poly.jpg",
    previewWebp: "/art-style-thumbnails/gemstone-poly.webp",
    previewAvif: "/art-style-thumbnails/gemstone-poly.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 24,
    prompt: "Recreate the exact image as a Minecraft-style voxel diorama. Preserve full composition and silhouette. Rebuild forms with hard cubic voxels (no bevels) at 2–8 px scale; use smaller voxels only for eyes/logos/hands. Apply matte, pixelated textures (no photo gradients), soft even lighting with ambient occlusion in creases, and a faint ground grid shadow. Keep silhouettes clean—no noisy fragmentation.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "claymation-sculpt",
  slug: "claymation-sculpt",
  name: "Claymation Sculpt",
  tone: "stylized",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Stop-motion clay portraiture with hand-molded texture and studio lighting.",
  marketingCopy: "Give portraits a tactile claymation finish with thumbprint detail, sculpted cuts, and warm tabletop light.",
  badges: ["whimsical"],
  requiredTier: "creator",
  sortOrder: 90,
  assets: {
    thumbnail: "/art-style-thumbnails/3d-storybook.jpg",
    thumbnailWebp: "/art-style-thumbnails/3d-storybook.webp",
    thumbnailAvif: "/art-style-thumbnails/3d-storybook.avif",
    preview: "/art-style-thumbnails/3d-storybook.jpg",
    previewWebp: "/art-style-thumbnails/3d-storybook.webp",
    previewAvif: "/art-style-thumbnails/3d-storybook.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 25,
    prompt: "Recreate the exact image as a stop-motion clay portrait — chunky, handmade, and charming. Preserve the subject’s full composition and proportions with a clean silhouette. Model forms as soft clay volumes with visible thumbprints, tool marks, and light seam lines; keep facial/details readable with sharper clay cuts. Use matte, saturated colors with subtle plasticine sheen; no photographic texture. Add tabletop studio lighting (soft key + tiny speculars) and a simple backdrop card. The result should feel like a frame from a claymation film — playful, tactile, and alive.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "artisan-charcoal",
  slug: "artisan-charcoal",
  name: "Artisan Charcoal",
  tone: "classic",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Hand-drawn charcoal artistry with dramatic shading.",
  marketingCopy: "Sculpt dramatic portraits with handcrafted charcoal shading.",
  badges: ["sketch"],
  requiredTier: "creator",
  sortOrder: 40,
  assets: {
    thumbnail: "/art-style-thumbnails/artisan-charcoal.jpg",
    thumbnailWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    thumbnailAvif: "/art-style-thumbnails/artisan-charcoal.avif",
    preview: "/art-style-thumbnails/artisan-charcoal.jpg",
    previewWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    previewAvif: "/art-style-thumbnails/artisan-charcoal.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 8,
    prompt: "Recreate the exact image as a detailed charcoal sketch — textured, hand-drawn, and expressive. Preserve the full structure and composition of the original subject, including accurate proportions, angles, and spatial arrangement. Use rich crosshatching, soft smudging, and tonal shading to build form and depth, mimicking traditional charcoal on textured paper. Keep the subject's details clear and intact while rendering them in a warm, monochromatic palette. The result should feel timeless and handcrafted, like a finely rendered charcoal illustration that blends realism with artistic character.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "classic-crayon",
  slug: "classic-crayon",
  name: "Classic Crayon",
  tone: "classic",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Layered crayon strokes with nostalgic paper grain and hand-drawn warmth.",
  marketingCopy: "Blend soft waxy hues and storybook charm for a handcrafted crayon keepsake.",
  badges: ["classic"],
  requiredTier: "creator",
  sortOrder: 50,
  assets: {
    thumbnail: "/art-style-thumbnails/artisan-charcoal.jpg",
    thumbnailWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    thumbnailAvif: "/art-style-thumbnails/artisan-charcoal.avif",
    preview: "/art-style-thumbnails/artisan-charcoal.jpg",
    previewWebp: "/art-style-thumbnails/artisan-charcoal.webp",
    previewAvif: "/art-style-thumbnails/artisan-charcoal.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 12,
    prompt: "Recreate the exact image as a hand-drawn crayon illustration — warm, waxy, and richly textured. Preserve the full composition and subject structure. Render forms with layered crayon strokes. Use a balanced color palette that matches the original image while allowing gentle artistic exaggeration; build shadows with cross-hatching and stacked complementary colors rather than flat black. The final image should read as a crisp, expressive crayon portrait — colorful, tactile, and true to the original photo.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "neon-splash",
  slug: "neon-splash",
  name: "Neon Splash",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Electric neon splashes with vibrant energy.",
  marketingCopy: "Ignite your portrait with neon streaks and kinetic color.",
  badges: ["neon"],
  sortOrder: 70,
  assets: {
    thumbnail: "/art-style-thumbnails/neon-splash.jpg",
    thumbnailWebp: "/art-style-thumbnails/neon-splash.webp",
    thumbnailAvif: "/art-style-thumbnails/neon-splash.avif",
    preview: "/art-style-thumbnails/neon-splash.jpg",
    previewWebp: "/art-style-thumbnails/neon-splash.webp",
    previewAvif: "/art-style-thumbnails/neon-splash.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 10,
    prompt: "Recreate the exact image in a dynamic Neon Splash style — electric, expressive, and bursting with high-intensity energy. Preserve the full subject composition, pose, and proportions with accurate facial features and visual structure. Surround the scene with vivid neon paint splashes, glowing outlines, and abstract light trails that radiate from the subject. Use a high-contrast color palette with hot pinks, electric blues, purples, and glowing oranges. Incorporate kinetic strokes, scatter effects, and surreal lighting to convey movement and emotion. The final image should feel like a glowing explosion of joy, power, and motion — where color and light collide in a captivating, artistic storm",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "electric-bloom",
  slug: "electric-bloom",
  name: "Electric Bloom",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Luminous bloom effects with electric color palettes.",
  marketingCopy: "Flood the canvas with vivid blooms and luminous lighting.",
  badges: ["glow"],
  sortOrder: 80,
  assets: {
    thumbnail: "/art-style-thumbnails/electric-bloom.jpg",
    thumbnailWebp: "/art-style-thumbnails/electric-bloom.webp",
    thumbnailAvif: "/art-style-thumbnails/electric-bloom.avif",
    preview: "/art-style-thumbnails/electric-bloom.jpg",
    previewWebp: "/art-style-thumbnails/electric-bloom.webp",
    previewAvif: "/art-style-thumbnails/electric-bloom.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 11,
    prompt: "Recreate this exact image as electric glow neon art — with the subject outlined in glowing lines, surrounded by radiant highlights and pulsing neon energy. Maintain the subject's exact pose, facial details, and composition, while enhancing it with bold contrast, vibrant lighting, and an expressive aura. Use high-energy light trails, edge-lit glow, and a mix of fluorescent and electric tones to evoke a sense of power and presence — like a vivid memory lit from within.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "electric-drip",
  slug: "electric-drip",
  name: "Electric Drip",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "UV neon drips and splatters with glowing rim lights and kinetic sprays.",
  marketingCopy: "Splash portraits in fluorescent drips, gravity streaks, and neon bloom for electric gallery energy.",
  badges: ["neon"],
  sortOrder: 85,
  assets: {
    thumbnail: "/art-style-thumbnails/neon-splash.jpg",
    thumbnailWebp: "/art-style-thumbnails/neon-splash.webp",
    thumbnailAvif: "/art-style-thumbnails/neon-splash.avif",
    preview: "/art-style-thumbnails/neon-splash.jpg",
    previewWebp: "/art-style-thumbnails/neon-splash.webp",
    previewAvif: "/art-style-thumbnails/neon-splash.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 27,
    prompt: "Recreate the exact image as a UV-neon drip/splatter painting. Preserve the full structure of the subject with a clean silhouette. Fluorescent accents: hot pink, electric blue, acid green, violet, and citrus orange. Build bold color fields, then layer sprays, splatter bursts, and gravity drips. Add soft neon bloom and thin rim-light glow along fast contours; use overspray speckle sparingly.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "abstract-fusion",
  slug: "abstract-fusion",
  name: "Abstract Fusion",
  tone: "abstract",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Bold geometric abstraction with luminous color blocking.",
  marketingCopy: "Blend geometry and color for energetic abstract compositions.",
  badges: ["abstract"],
  sortOrder: 100,
  assets: {
    thumbnail: "/art-style-thumbnails/abstract-fusion.jpg",
    thumbnailWebp: "/art-style-thumbnails/abstract-fusion.webp",
    thumbnailAvif: "/art-style-thumbnails/abstract-fusion.avif",
    preview: "/art-style-thumbnails/abstract-fusion.jpg",
    previewWebp: "/art-style-thumbnails/abstract-fusion.webp",
    previewAvif: "/art-style-thumbnails/abstract-fusion.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 13,
    prompt: "Create abstract fusion art by blending watercolor, digital textures, and geometric patterns into a cohesive, expressive, multi-style composition. CRITICAL: Preserve the EXACT same person - same face, same eye color, same expression, same proportions, same pose. Do not alter any facial features, anatomical structure, or identifying characteristics.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "gemstone-poly",
  slug: "gemstone-poly",
  name: "Gemstone Poly",
  tone: "electric",
  tier: "free",
  category: "style",
  isPremium: false,
  defaultUnlocked: true,
  priceModifier: 0,
  description: "Low-poly crystalline facets with gemstone brilliance.",
  marketingCopy: "Cut portraits into shimmering gemstone-inspired facets.",
  badges: ["facet"],
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/gemstone-poly.jpg",
    thumbnailWebp: "/art-style-thumbnails/gemstone-poly.webp",
    thumbnailAvif: "/art-style-thumbnails/gemstone-poly.avif",
    preview: "/art-style-thumbnails/gemstone-poly.jpg",
    previewWebp: "/art-style-thumbnails/gemstone-poly.webp",
    previewAvif: "/art-style-thumbnails/gemstone-poly.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 6,
    prompt: "Recreate the exact image as an artistic low poly illustration — colorful, faceted, and compositionally accurate. Preserve the full subject structure, including precise pose, facial features, proportions, and spatial layout. Break the image into angular geometric polygons of varied sizes, using bold color blocking and gradient transitions to reflect natural shading. Emphasize artistic abstraction through clean edges and stylized fragmentation, while maintaining visual clarity and realism in the subject. The result should feel modern and decorative — like a vibrant digital mosaic that's both expressive and true to the original form.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "deco-luxe",
  slug: "deco-luxe",
  name: "Deco Luxe",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Art Deco elegance with geometric luxury.",
  marketingCopy: "Unlock gilded Art Deco geometry, mirrored sheen, and couture lighting for statement canvases.",
  badges: ["luxury"],
  requiredTier: "creator",
  sortOrder: 110,
  assets: {
    thumbnail: "/art-style-thumbnails/deco-luxe.jpg",
    thumbnailWebp: "/art-style-thumbnails/deco-luxe.webp",
    thumbnailAvif: "/art-style-thumbnails/deco-luxe.avif",
    preview: "/art-style-thumbnails/deco-luxe.jpg",
    previewWebp: "/art-style-thumbnails/deco-luxe.webp",
    previewAvif: "/art-style-thumbnails/deco-luxe.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 15,
    prompt: "Recreate the exact image in a bold, modern Art Deco style — a dramatic fusion of classic glamour and contemporary edge. Maintain the subject's full composition, pose, and spatial layout with high fidelity. Apply rich, dimensional lighting and sharp, clean linework to create a sense of depth and visual focus. Use strong geometric framing, symmetry, and gold accents to echo iconic Deco architecture, balanced with smooth digital gradients and matte finishes. Emphasize a luxury palette — including deep teal, navy, black, gold, blush, and cream — for a sophisticated, high-impact aesthetic. The result should feel like a cinematic poster or luxury magazine cover: expressive, powerful, and timelessly stylish.",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
},
{
  id: "signature-aurora",
  slug: "signature-aurora",
  name: "Aurora Signature",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 10,
  description: "Premium aurora gradients layered with hand-painted highlights.",
  marketingCopy: "Unlock Wondertone’s signature finish with luminous aurora light.",
  badges: ["exclusive","new"],
  requiredTier: "plus",
  sortOrder: 120,
  assets: {
    thumbnail: "/art-style-thumbnails/signature-aurora.jpg",
    thumbnailWebp: null,
    thumbnailAvif: null,
    preview: "/art-style-thumbnails/signature-aurora.jpg",
    previewWebp: null,
    previewAvif: null,
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
},
{
  id: "porcelain-figurine",
  slug: "porcelain-figurine",
  name: "Porcelain Figurine",
  tone: "signature",
  tier: "premium",
  category: "style",
  isPremium: true,
  defaultUnlocked: false,
  priceModifier: 0,
  description: "Glazed porcelain keepsake with rounded forms, gold trims, and collector sheen.",
  marketingCopy: "Transform portraits into heirloom porcelain figurines with pastel glaze, jewel accents, and gilded edges.",
  badges: ["exclusive"],
  requiredTier: "creator",
  sortOrder: 130,
  assets: {
    thumbnail: "/art-style-thumbnails/pastel-bliss.jpg",
    thumbnailWebp: "/art-style-thumbnails/pastel-bliss.webp",
    thumbnailAvif: "/art-style-thumbnails/pastel-bliss.avif",
    preview: "/art-style-thumbnails/pastel-bliss.jpg",
    previewWebp: "/art-style-thumbnails/pastel-bliss.webp",
    previewAvif: "/art-style-thumbnails/pastel-bliss.avif",
  },
  featureFlags: {
    isEnabled: true,
    rolloutPercentage: 100,
    disabledReason: null,
  },
  prompt: {
    numericId: 28,
    prompt: "Recreate the exact image as a glazed porcelain/ceramic figurine — glossy, delicate, and collectible. Preserve full structure and pose, then smooth forms to rounded, toy-like geometry. Coat surfaces with high-gloss glaze: tight specular highlights, pooling at creases, and tiny pinhole bubbles; add gold luster edge trims sparingly. Use a curated pastel palette with 1–2 jewel accents. Place on a soft tabletop shadow. The result should feel like a premium ceramic keepsake",
    updatedAt: "2025-10-16 07:13:28.066242+00",
  },
}
];

export const STYLE_REGISTRY_BY_ID = new Map(STYLE_REGISTRY.map((style) => [style.id, style]));

export const STYLE_REGISTRY_BY_NUMERIC_ID = new Map(
  STYLE_REGISTRY.filter((style) => style.prompt).map((style) => [style.prompt!.numericId, style])
);
