// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvjganetpyyrguuxjtqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2amdhbmV0cHl5cmd1dXhqdHFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Nzg3NzUsImV4cCI6MjA2NjE1NDc3NX0.Bl_LdqqBh9FvS6oecP28gBQOxhyj-XE48YFAvT5Y6YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);