name: Wondertone CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  prepare:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-wondertone-${{ hashFiles('package-lock.json') }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run test
        env:
          CI: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run build:analyze
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wondertone-dist
          path: dist

  bundle-size:
    name: Enforce Bundle Budgets
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: wondertone-dist
          path: dist
      - name: Validate bundle sizes
        run: node scripts/verify-bundle-sizes.cjs
